(self.AMP=self.AMP||[]).push({n:"amp-form",v:"2004071640410",f:(function(AMP,_){
var l,aa="function"==typeof Object.create?Object.create:function(a){function b(){}b.prototype=a;return new b},ba;if("function"==typeof Object.setPrototypeOf)ba=Object.setPrototypeOf;else{var ca;a:{var da={a:!0},ea={};try{ea.__proto__=da;ca=ea.a;break a}catch(a){}ca=!1}ba=ca?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}var fa=ba;
function n(a,b){a.prototype=aa(b.prototype);a.prototype.constructor=a;if(fa)fa(a,b);else for(var c in b)if("prototype"!=c)if(Object.defineProperties){var d=Object.getOwnPropertyDescriptor(b,c);d&&Object.defineProperty(a,c,d)}else a[c]=b[c];a.Ua=b.prototype};function ha(a,b){b=void 0===b?"":b;try{return decodeURIComponent(a)}catch(c){return b}};var ia=/(?:^[#?]?|&)([^=&]+)(?:=([^&]*))?/g;function ja(a){var b=Object.create(null);if(!a)return b;for(var c;c=ia.exec(a);){var d=ha(c[1],c[1]),e=c[2]?ha(c[2].replace(/\+/g," "),c[2]):"";b[d]=e}return b};var ka=Object.prototype.toString;function la(a){return a?Array.prototype.slice.call(a):[]};var p=self.AMP_CONFIG||{},ma=("string"==typeof p.cdnProxyRegex?new RegExp(p.cdnProxyRegex):p.cdnProxyRegex)||/^https:\/\/([a-zA-Z0-9_-]+\.)?cdn\.ampproject\.org$/;function na(a){if(!self.document||!self.document.head||self.location&&ma.test(self.location.origin))return null;var b=self.document.head.querySelector('meta[name="'+a+'"]');return b&&b.getAttribute("content")||null}
var oa={thirdParty:p.thirdPartyUrl||"https://3p.ampproject.net",thirdPartyFrameHost:p.thirdPartyFrameHost||"ampproject.net",thirdPartyFrameRegex:("string"==typeof p.thirdPartyFrameRegex?new RegExp(p.thirdPartyFrameRegex):p.thirdPartyFrameRegex)||/^d-\d+\.ampproject\.net$/,cdn:p.cdnUrl||na("runtime-host")||"https://cdn.ampproject.org",cdnProxyRegex:ma,localhostRegex:/^https?:\/\/localhost(:\d+)?$/,errorReporting:p.errorReportingUrl||"https://amp-error-reporting.appspot.com/r",localDev:p.localDev||
!1,trustedViewerHosts:[/(^|\.)google\.(com?|[a-z]{2}|com?\.[a-z]{2}|cat)$/,/(^|\.)gmail\.(com|dev)$/],geoApi:p.geoApiUrl||na("amp-geo-api")};self.__AMP_LOG=self.__AMP_LOG||{user:null,dev:null,userForEmbed:null};var q=self.__AMP_LOG;function r(){if(!q.user)throw Error("failed to call initLogConstructor");return q.user}function t(){if(q.dev)return q.dev;throw Error("failed to call initLogConstructor");}function u(a,b,c,d){r().assert(a,b,c,d,void 0,void 0,void 0,void 0,void 0,void 0,void 0)};function pa(){var a,b;this.promise=new Promise(function(c,d){a=c;b=d});this.resolve=a;this.reject=b}function qa(a){return new Promise(function(b){b(a())})}function ra(){var a,b,c;this.wa=new Promise(function(a,d){b=a;c=d});this.Ka=b;this.Ia=c;this.ga=0;if(a)for(var d=0;d<a.length;d++)this.add(a[d])}ra.prototype.add=function(a){var b=this,c=++this.ga;Promise.resolve(a).then(function(a){b.ga===c&&b.Ka(a)},function(a){b.ga===c&&b.Ia(a)});return this.wa};
ra.prototype.then=function(a,b){return this.wa.then(a,b)};var sa=Object.prototype.hasOwnProperty;function v(){var a,b=Object.create(null);a&&Object.assign(b,a);return b}function w(a){return a||{}}
function ta(a,b){var c=void 0===c?10:c;var d=[],e=[];e.push({t:a,s:b,d:0});for(a={};0<e.length;){b=e.shift();a.G=b.t;a.B=b.s;a.W=b.d;if(d.includes(a.B))throw Error("Source object has a circular reference.");d.push(a.B);a.G!==a.B&&(a.W>c?Object.assign(a.G,a.B):Object.keys(a.B).forEach(function(a){return function(b){var c=a.B[b];if(sa.call(a.G,b)){var d=a.G[b];if("[object Object]"===ka.call(c)&&"[object Object]"===ka.call(d)){e.push({t:d,s:c,d:a.W+1});return}}a.G[b]=c}}(a)));a={B:a.B,G:a.G,W:a.W}}}
;function x(){var a=100;this.Fa=a;this.fa=this.ma=0;this.Z=Object.create(null)}x.prototype.has=function(a){return!!this.Z[a]};x.prototype.get=function(a){var b=this.Z[a];if(b)return b.access=++this.fa,b.payload};x.prototype.put=function(a,b){this.has(a)||this.ma++;this.Z[a]={payload:b,access:this.fa};if(!(this.ma<=this.Fa)){t().warn("lru-cache","Trimming LRU cache");a=this.Z;var c=this.fa+1,d;for(d in a){var e=a[d].access;if(e<c){c=e;var f=d}}void 0!==f&&(delete a[f],this.ma--)}};function ua(a,b){return b.length>a.length?!1:0==a.lastIndexOf(b,0)};var va=w({c:!0,v:!0,a:!0,ad:!0,action:!0}),wa,xa,ya=/[?&]amp_js[^&]*/,za=/[?&]amp_gsa[^&]*/,Aa=/[?&]amp_r[^&]*/,Ba=/[?&]amp_kit[^&]*/,Ca=/[?&]usqp[^&]*/;
function y(a){var b;wa||(wa=self.document.createElement("a"),xa=self.__AMP_URL_CACHE||(self.__AMP_URL_CACHE=new x));var c=b?null:xa,d=wa;if(c&&c.has(a))a=c.get(a);else{d.href=a;d.protocol||(d.href=d.href);var e={href:d.href,protocol:d.protocol,host:d.host,hostname:d.hostname,port:"0"==d.port?"":d.port,pathname:d.pathname,search:d.search,hash:d.hash,origin:null};"/"!==e.pathname[0]&&(e.pathname="/"+e.pathname);if("http:"==e.protocol&&80==e.port||"https:"==e.protocol&&443==e.port)e.port="",e.host=e.hostname;
e.origin=d.origin&&"null"!=d.origin?d.origin:"data:"!=e.protocol&&e.host?e.protocol+"//"+e.host:e.href;c&&c.put(a,e);a=e}return a}function Da(a,b,c){if(!b)return a;var d=a.split("#",2),e=d[0].split("?",2),f=e[0]+(e[1]?c?"?"+b+"&"+e[1]:"?"+e[1]+"&"+b:"?"+b);return f+=d[1]?"#"+d[1]:""}
function Ea(a){var b=[],c;for(c in a){var d=a[c];if(null!=d)if(Array.isArray(d))for(var e=0;e<d.length;e++){var f=d[e];b.push(encodeURIComponent(c)+"="+encodeURIComponent(f))}else e=d,b.push(encodeURIComponent(c)+"="+encodeURIComponent(e))}return b.join("&")}function Fa(a){"string"==typeof a&&(a=y(a));return oa.cdnProxyRegex.test(a.origin)};function Ga(a,b){if(a.__AMP__EXPERIMENT_TOGGLES)var c=a.__AMP__EXPERIMENT_TOGGLES;else{a.__AMP__EXPERIMENT_TOGGLES=Object.create(null);c=a.__AMP__EXPERIMENT_TOGGLES;if(a.AMP_CONFIG)for(var d in a.AMP_CONFIG){var e=a.AMP_CONFIG[d];"number"===typeof e&&0<=e&&1>=e&&(c[d]=Math.random()<e)}if(a.AMP_CONFIG&&Array.isArray(a.AMP_CONFIG["allow-doc-opt-in"])&&0<a.AMP_CONFIG["allow-doc-opt-in"].length&&(d=a.AMP_CONFIG["allow-doc-opt-in"],e=a.document.head.querySelector('meta[name="amp-experiments-opt-in"]'))){e=
e.getAttribute("content").split(",");for(var f=0;f<e.length;f++)-1!=d.indexOf(e[f])&&(c[e[f]]=!0)}Object.assign(c,Ha(a));if(a.AMP_CONFIG&&Array.isArray(a.AMP_CONFIG["allow-url-opt-in"])&&0<a.AMP_CONFIG["allow-url-opt-in"].length)for(d=a.AMP_CONFIG["allow-url-opt-in"],a=ja(a.location.originalHash||a.location.hash),e=0;e<d.length;e++)f=a["e-"+d[e]],"1"==f&&(c[d[e]]=!0),"0"==f&&(c[d[e]]=!1)}var g=c;return!!g[b]}
function Ha(a){var b="";try{"localStorage"in a&&(b=a.localStorage.getItem("amp-experiment-toggles"))}catch(e){t().warn("EXPERIMENTS","Failed to retrieve experiments from localStorage.")}var c=b?b.split(/\s*,\s*/g):[];a=Object.create(null);for(var d=0;d<c.length;d++)0!=c[d].length&&("-"==c[d][0]?a[c[d].substr(1)]=!1:a[c[d]]=!0);return a};var Ia={},A=(Ia["ampdoc-fie"]={isTrafficEligible:function(){return!0},branches:[["21065001"],["21065002"]]},Ia);function B(a,b){var c=a.ownerDocument.defaultView,d=c.__AMP_TOP||(c.__AMP_TOP=c),e=c!=d;var f=d;if(Ga(f,"ampdoc-fie")){f.__AMP_EXPERIMENT_BRANCHES=f.__AMP_EXPERIMENT_BRANCHES||{};for(var g in A)if(sa.call(A,g)&&!sa.call(f.__AMP_EXPERIMENT_BRANCHES,g))if(A[g].isTrafficEligible&&A[g].isTrafficEligible(f)){if(!f.__AMP_EXPERIMENT_BRANCHES[g]&&Ga(f,g)){var h=A[g].branches;f.__AMP_EXPERIMENT_BRANCHES[g]=h[Math.floor(Math.random()*h.length)]||null}}else f.__AMP_EXPERIMENT_BRANCHES[g]=null;f="21065002"===
(f.__AMP_EXPERIMENT_BRANCHES?f.__AMP_EXPERIMENT_BRANCHES["ampdoc-fie"]:null)}else f=!1;var k=f;e&&!k?b=Ja(c,b)?C(c,b):null:(a=D(a),a=E(a),b=Ja(a,b)?C(a,b):null);return b}function F(a,b){a=a.__AMP_TOP||(a.__AMP_TOP=a);return C(a,b)}function G(a,b){var c=D(a);c=E(c);return C(c,b)}function Ka(a,b){return La(E(a),b)}function D(a){return a.nodeType?F((a.ownerDocument||a).defaultView,"ampdoc").getAmpDoc(a):a}function E(a){a=D(a);return a.isSingleDoc()?a.win:a}
function C(a,b){Ja(a,b);var c=Ma(a);a=c[b];a.obj||(a.obj=new a.ctor(a.context),a.ctor=null,a.context=null,a.resolve&&a.resolve(a.obj));return a.obj}function Na(a,b){var c=La(a,b);if(c)return c;a=Ma(a);a[b]=Oa();return a[b].promise}function La(a,b){var c=Ma(a)[b];if(c){if(c.promise)return c.promise;C(a,b);return c.promise=Promise.resolve(c.obj)}return null}function Ma(a){var b=a.__AMP_SERVICES;b||(b=a.__AMP_SERVICES={});return b}
function Ja(a,b){a=a.__AMP_SERVICES&&a.__AMP_SERVICES[b];return!(!a||!a.ctor&&!a.obj)}function Oa(){var a=new pa,b=a,c=b.promise,d=b.resolve;b=b.reject;c.catch(function(){});return{obj:null,promise:c,resolve:d,reject:b,context:null,ctor:null}};/*
 https://mths.be/cssescape v1.5.1 by @mathias | MIT license */
var Pa=/(\0)|^(-)$|([\x01-\x1f\x7f]|^-?[0-9])|([\x80-\uffff0-9a-zA-Z_-]+)|[^]/g;function Qa(a,b,c,d,e){return e?e:b?"\ufffd":d?a.slice(0,-1)+"\\"+a.slice(-1).charCodeAt(0).toString(16)+" ":"\\"+a};var Ra;function Sa(a,b){for(var c=[],d=a.parentElement;d;d=d.parentElement)b(d)&&c.push(d);return c}function Ta(a){var b="fieldset";/^[\w-]+$/.test(b);b=b.toUpperCase();return Sa(a,function(a){return a.tagName==b})}function H(a,b){for(var c=a.length,d=0;d<c;d++)b(a[d],d)};function Ua(a,b,c){var d=Ka(a,b);if(d)return d;var e=D(a);return e.waitForBodyOpen().then(function(){var a=e.win;var b=e.win.document.head;if(b){var d={};b=b.querySelectorAll("script[custom-element],script[custom-template]");for(var k=0;k<b.length;k++){var m=b[k];m=m.getAttribute("custom-element")||m.getAttribute("custom-template");d[m]=!0}d=Object.keys(d)}else d=[];a=d.includes(c)?F(a,"extensions").waitForExtension(a,c):Promise.resolve();return a}).then(function(){var d=e.win;return d.__AMP_EXTENDED_ELEMENTS&&
d.__AMP_EXTENDED_ELEMENTS[c]?Na(E(a),b):null})};function I(a){return G(a,"mutator")};var Va,Wa="Webkit webkit Moz moz ms O o".split(" ");function Xa(a,b,c){var d;var e=a.style;if(!ua(b,"--")){Va||(Va=v());var f=Va[b];if(!f){f=b;if(void 0===e[b]){var g=b.charAt(0).toUpperCase()+b.slice(1);b:{for(var h=0;h<Wa.length;h++){var k=Wa[h]+g;if(void 0!==e[k]){g=k;break b}}g=""}void 0!==e[g]&&(f=g)}Va[b]=f}b=f}if(b){var m=d?c+d:c;ua(b,"--")?a.style.setProperty(b,m):a.style[b]=m}}
function Ya(a,b){void 0===b&&(b=a.hasAttribute("hidden"));b?a.removeAttribute("hidden"):a.setAttribute("hidden","")};var J;function Za(a,b,c){var d=void 0,e=a,f=c;var g=function(a){try{return f(a)}catch(z){throw self.__AMP_REPORT_ERROR(z),z;}};var h=$a(),k=!1;d&&(k=d.capture);e.addEventListener(b,g,h?d:k);return function(){e&&e.removeEventListener(b,g,h?d:k);g=e=f=null}}function $a(){if(void 0!==J)return J;J=!1;try{var a={get capture(){J=!0}};self.addEventListener("test-options",null,a);self.removeEventListener("test-options",null,a)}catch(b){}return J};function ab(a,b,c,d){var e={detail:c};Object.assign(e,d);if("function"==typeof a.CustomEvent)return new a.CustomEvent(b,e);a=a.document.createEvent("CustomEvent");a.initCustomEvent(b,!!e.bubbles,!!e.cancelable,c);return a}function bb(a,b,c){return Za(a,b,c)}function cb(a,b){var c=b,d=Za(a,"mouseup",function(a){try{c(a)}finally{c=null,d()}});return d}function db(a){var b,c,d=new Promise(function(b){c=cb(a,b)});d.then(c,c);b&&b(c);return d};function fb(a,b){function c(c){g=null;f=a.setTimeout(d,e);b.apply(null,c)}function d(){f=0;g&&c(g)}var e=100,f=0,g=null;return function(a){for(var b=[],d=0;d<arguments.length;++d)b[d-0]=arguments[d];f?g=b:c(b)}};function gb(a){var b=a.getRootNode();this.Ga=b.ownerDocument||b;this.j=this.Ga.defaultView;this.oa=G(a,"viewport");this.S=[];this.S.push(bb(b,"input",function(a){a=a.target;"TEXTAREA"==a.tagName&&a.hasAttribute("autoexpand")&&hb(a)}));this.S.push(bb(b,"mousedown",function(a){1==a.which&&(a=a.target,"TEXTAREA"==a.tagName&&ib(a))}));var c=b.querySelectorAll("textarea");this.S.push(bb(b,"amp:dom-update",function(){c=b.querySelectorAll("textarea")}));var d=fb(this.j,function(a){a.relayoutAll&&jb(c)});
this.S.push(this.oa.onResize(d));kb(c)}function lb(a){function b(){var b=c.querySelector("textarea[autoexpand]");b&&!d?d=new gb(a):!b&&d&&(d.dispose(),d=null)}var c=a.getRootNode(),d=null;Za(c,"amp:dom-update",b);b()}gb.prototype.dispose=function(){this.S.forEach(function(a){return a()})};
function kb(a){Promise.all(la(a).map(function(a){return mb(a).then(function(b){b&&(r().warn("AMP-FORM",'"textarea[autoexpand]" with initially scrolling content will not autoexpand.\nSee https://github.com/ampproject/amphtml/issues/20839'),a.removeAttribute("autoexpand"))})}))}function mb(a){var b=I(a);return b.measureElement(function(){return a.scrollHeight>a.clientHeight})}function jb(a){H(a,function(a){"TEXTAREA"==a.tagName&&a.hasAttribute("autoexpand")&&hb(a)})}
function ib(a){var b=I(a);Promise.all([b.measureElement(function(){return a.scrollHeight}),db(a)]).then(function(c){var d=c[0],e=0;return b.measureMutateElement(a,function(){e=a.scrollHeight},function(){d!=e&&a.removeAttribute("autoexpand")})})}
function hb(a){var b=I(a),c=a.ownerDocument.defaultView,d=0,e=0,f=0,g=nb(a);b.measureMutateElement(a,function(){var b=c.getComputedStyle(a)||v();e=a.scrollHeight;var g=parseInt(b.getPropertyValue("max-height"),10);f=isNaN(g)?Infinity:g;d="content-box"==b.getPropertyValue("box-sizing")?-parseInt(b.getPropertyValue("padding-top"),10)+-parseInt(b.getPropertyValue("padding-bottom"),10):parseInt(b.getPropertyValue("border-top-width"),10)+parseInt(b.getPropertyValue("border-bottom-width"),10)},function(){return g.then(function(b){a.classList.toggle("i-amphtml-textarea-max",
b+d>f);var c="iAmphtmlHasExpanded"in a.dataset,g=c||e<=b;g&&(a.dataset.iAmphtmlHasExpanded="",Xa(a,"height",b+d+"px"))})})}
function nb(a){var b=a.ownerDocument,c=b.defaultView,d=b.body,e=I(a),f=a.cloneNode(!1);f.classList.add("i-amphtml-textarea-clone");var g=0,h=0,k=!1;return e.measureMutateElement(d,function(){var b=c.getComputedStyle(a)||v(),d=parseInt(b.getPropertyValue("max-height"),10);g=parseInt(b.getPropertyValue("width"),10);k=isNaN(d)||a.scrollHeight<d},function(){k&&(a.scrollTop=0);Xa(f,"width",g+"px");b.body.appendChild(f)}).then(function(){return e.measureMutateElement(d,function(){h=f.scrollHeight},function(){var a=
f;a.parentElement&&a.parentElement.removeChild(a)})}).then(function(){return h})};function K(a){for(var b=a.elements,c={},d=/^(?:input|select|textarea)$/i,e=/^(?:submit|button|image|file|reset)$/i,f=/^(?:checkbox|radio)$/i,g={},h=0;h<b.length;g={F:g.F},h++){var k=b[h],m=k,z=m.checked;g.F=m.name;var gc=m.multiple,hc=m.options,ic=m.tagName,eb=m.type;m=m.value;!g.F||ob(k)||!d.test(ic)||e.test(eb)||f.test(eb)&&!z||(void 0===c[g.F]&&(c[g.F]=[]),gc?H(hc,function(a){return function(b){b.selected&&c[a.F].push(b.value)}}(g)):c[g.F].push(m))}var R=pb(a);R&&R.name&&(a=R.name,void 0===c[a]&&
(c[a]=[]),c[R.name].push(R.value));Object.keys(c).forEach(function(a){0==c[a].length&&delete c[a]});return c}function pb(a){var b=a.elements,c=b.length,d=a.ownerDocument.activeElement,e=null;for(a=0;a<c;a++){var f=b[a],g=f.type;if("BUTTON"==f.tagName||"submit"==g)if(e||(e=f),d==f)return d}return e}function ob(a){if(a.disabled)return!0;a=Ta(a);for(var b=0;b<a.length;b++)if(a[b].disabled)return!0;return!1}
function qb(a){switch(a.type){case "select-multiple":case "select-one":a=a.options;for(var b=0;b<a.length;b++)if(a[b].selected!==a[b].defaultSelected)return!1;break;case "checkbox":case "radio":return a.checked===a.defaultChecked;default:return a.value===a.defaultValue}return!0};function rb(a,b){return a.hasAttribute("verify-xhr")?new sb(a,b):new tb(a)}function L(a){this.h=a}L.prototype.onCommit=function(){ub(this);a:{var a=this.h.elements;for(var b=0;b<a.length;b++){var c=a[b];if(!c.disabled&&!qb(c)){a=!0;break a}}a=!1}return a?this.za():Promise.resolve({updatedElements:[],errors:[]})};L.prototype.za=function(){return Promise.resolve({updatedElements:[],errors:[]})};function ub(a){(a=a.h.elements)&&H(a,function(a){a.setCustomValidity("")})}
function tb(){L.apply(this,arguments)}n(tb,L);function sb(a,b){this.h=a;this.aa=b;this.V=null;this.va=[]}n(sb,L);sb.prototype.za=function(){var a=this,b=this.aa().then(function(){return[]},function(a){return vb(a)});return wb(this,b).then(function(b){return xb(a,b)})};function wb(a,b){if(!a.V){a.V=new ra;var c=function(){return a.V=null};a.V.then(c,c)}return a.V.add(b)}
function xb(a,b){function c(a){return b.every(function(b){return a.name!==b.name})}var d=[],e=a.va;a.va=b;for(var f=0;f<b.length;f++){var g=b[f],h=r().assertString(g.name,"Verification errors must have a name property");g=r().assertString(g.message,"Verification errors must have a message property");h=r().assertElement(a.h.querySelector('[name="'+h+'"]'),"Verification error name property must match a field name");h.checkValidity()&&(h.setCustomValidity(g),d.push(h))}var k=e.filter(c).map(function(b){return a.h.querySelector('[name="'+
b.name+'"]')});return{updatedElements:d.concat(k),errors:b}}function vb(a){return(a=a.response)?a.json().then(function(a){return a.verifyErrors||[]},function(){return[]}):Promise.resolve([])};function yb(a,b){var c=F(a,"platform");return c.isIos()&&11==c.getMajorVersion()?new zb(b):FormData.prototype.entries&&FormData.prototype.delete?new M(b):new N(b)}function N(a){this.C=a?K(a):v()}N.prototype.append=function(a,b){var c=String(a);this.C[c]=this.C[c]||[];this.C[c].push(String(b))};N.prototype.delete=function(a){delete this.C[a]};
N.prototype.entries=function(){var a=this,b=[];Object.keys(this.C).forEach(function(c){a.C[c].forEach(function(a){return b.push([c,a])})});var c=0;return{next:function(){return c<b.length?{value:b[c++],done:!1}:{value:void 0,done:!0}}}};N.prototype.getFormData=function(){var a=this,b=new FormData;Object.keys(this.C).forEach(function(c){a.C[c].forEach(function(a){return b.append(c,a)})});return b};function M(a){this.D=new FormData(a);a&&(a=pb(a))&&a.name&&this.append(a.name,a.value)}
M.prototype.append=function(a,b){this.D.append(a,b)};M.prototype.delete=function(a){this.D.delete(a)};M.prototype.entries=function(){return this.D.entries()};M.prototype.getFormData=function(){return this.D};function zb(a){M.call(this,a);var b=this;a&&H(a.elements,function(a){"file"==a.type&&0==a.files.length&&(b.D.delete(a.name),b.D.append(a.name,new Blob([]),""))})}n(zb,M);
zb.prototype.append=function(a,b,c){b&&"object"==typeof b&&""==b.name&&0==b.size?this.D.append(a,new Blob([]),c||""):this.D.append(a,b)};var Ab={INPUT:!0,SELECT:!0,TEXTAREA:!0};function Bb(a,b){this.h=a;this.j=b;this.P=0;this.K=v();this.na=null;this.Ba=this.ca=!1;this.la();for(a=0;a<this.h.elements.length;++a)Cb(this,this.h.elements[a]);O(this)}l=Bb.prototype;l.onSubmitting=function(){this.ca=!0;O(this)};l.onSubmitError=function(){this.ca=!1;O(this)};l.onSubmitSuccess=function(){this.ca=!1;this.na=yb(this.j,this.h).getFormData();this.K=v();this.P=0;O(this)};
function O(a){var b=0<a.P&&!a.ca;if(b!==a.Ba){a.h.classList.toggle("amp-form-dirty",b);var c=ab(a.j,"amp:form-dirtiness-change",w({isDirty:b}),{bubbles:!0});a.h.dispatchEvent(c)}a.Ba=b}l.la=function(){this.h.addEventListener("input",this.ua.bind(this));this.h.addEventListener("reset",this.Ha.bind(this));this.h.addEventListener("amp:form-value-change",this.ua.bind(this))};l.ua=function(a){Cb(this,a.target);O(this)};l.Ha=function(){this.K=v();this.P=0;O(this)};
function Cb(a,b){var c=b.hidden;if(Ab[b.tagName]&&b.name&&!c&&!ob(b)){a:switch(b.tagName){case "INPUT":c="checkbox"==b.type||"radio"==b.type?!b.checked:!b.value;break a;case "TEXTAREA":c=!b.value;break a;case "SELECT":c=!1;break a;default:throw Error("isFieldEmpty: "+b.tagName+" is not a supported field element.");}(c=c||qb(b))||(a.na?(c=b.value,c=a.na.get(b.name)===c):c=!1);c?(b=b.name,a.K[b]&&(a.K[b]=!1,--a.P)):(b=b.name,a.K[b]||(a.K[b]=!0,++a.P))}};function Db(){this.o=null}l=Db.prototype;l.add=function(a){var b=this;this.o||(this.o=[]);this.o.push(a);return function(){b.remove(a)}};l.remove=function(a){this.o&&(a=this.o.indexOf(a),-1<a&&this.o.splice(a,1))};l.removeAll=function(){this.o&&(this.o.length=0)};l.fire=function(a){if(this.o)for(var b=this.o,c=0;c<b.length;c++)(0,b[c])(a)};l.getHandlerCount=function(){return this.o?this.o.length:0};function Eb(){this.ta=new Db}Eb.prototype.beforeSubmit=function(a){return this.ta.add(a)};Eb.prototype.fire=function(a){this.ta.fire(a)};var Fb=["GET","POST"];function Gb(a){var b=a.getAttribute("crossorigin");return b&&"amp-viewer-auth-token-via-post"===b.trim()?Ua(a,"amp-viewer-assistance","amp-viewer-assistance").then(function(a){u(a,'crossorigin="amp-viewer-auth-token-post" requires amp-viewer-assistance extension.');return a.getIdTokenPromise()}).then(function(a){return a||""}).catch(function(){return""}):Promise.resolve(void 0)};function P(a,b){var c="amp-form";this.L=a;this.A=b;this.La=c}P.prototype.isEnabled=function(){var a=this.L.getAmpDoc();return a.isSingleDoc()&&a.getRootNode().documentElement.hasAttribute("allow-viewer-render-template")?this.L.hasCapability("viewerRenderTemplate"):!1};P.prototype.assertTrustedViewer=function(a){return this.L.isTrustedViewer().then(function(b){u(b,"Refused to attempt SSR in untrusted viewer: ",a)})};
P.prototype.ssr=function(a,b,c,d){var e=this;c=void 0===c?null:c;d=void 0===d?{}:d;var f;c||(f=this.A.maybeFindTemplate(a));return this.assertTrustedViewer(a).then(function(){return e.L.sendMessageAwaitResponse("viewerRenderTemplate",Hb(e,b,f,c,d))})};
P.prototype.applySsrOrCsrTemplate=function(a,b){var c=this;if(this.isEnabled()){u("string"===typeof b.html,"Server side html response must be defined");var d=this.assertTrustedViewer(a).then(function(){return c.A.findAndSetHtmlForTemplate(a,b.html)})}else d=Array.isArray(b)?this.A.findAndRenderTemplateArray(a,b):this.A.findAndRenderTemplate(a,b);return d};
function Hb(a,b,c,d,e){e=void 0===e?{}:e;var f=w({type:a.La}),g="successTemplate",h=d&&d[g]?d[g]:c;h&&(f[g]={type:"amp-mustache",payload:h.innerHTML});var k="errorTemplate",m=d&&d[k]?d[k]:null;m&&(f[k]={type:"amp-mustache",payload:m.innerHTML});e&&Object.assign(f,e);a=b.xhrUrl;c=b.fetchOpt;b=Object.assign({},c);if((d=c.body)&&"function"==typeof d.getFormData){c=c.body;b.headers["Content-Type"]="multipart/form-data;charset=utf-8";c=c.entries();d=[];for(e=c.next();!e.done;e=c.next())d.push(e.value);
b.body=d}return w({originalRequest:{input:a,init:b},ampComponent:f})};function Ib(a,b){this.ka=b;this.oa=G(a,"viewport");this.Aa=F(a.win,"vsync");this.ia=null;this.ha="";this.da=!1;this.J=a.win.document.createElement("div");Ya(this.J,!1);this.J.classList.add("i-amphtml-validation-bubble");this.J.__BUBBLE_OBJ=this;a.getBody().appendChild(this.J)}Ib.prototype.isActiveOn=function(a){return this.da&&a==this.ia};Ib.prototype.hide=function(){this.da&&(this.da=!1,this.ia=null,this.ha="",this.Aa.run({measure:void 0,mutate:Jb},{bubbleElement:this.J}))};
Ib.prototype.show=function(a,b){if(!this.isActiveOn(a)||b!=this.ha){this.da=!0;this.ia=a;this.ha=b;var c={message:b,targetElement:a,bubbleElement:this.J,viewport:this.oa,id:this.ka};this.Aa.run({measure:Kb,mutate:Lb},c)}};function Jb(a){a.bubbleElement.removeAttribute("aria-alert");a.bubbleElement.removeAttribute("role");for(var b=a.bubbleElement;b.firstChild;)b.removeChild(b.firstChild);Ya(a.bubbleElement,!1)}function Kb(a){a.targetRect=a.viewport.getLayoutRect(a.targetElement)}
function Lb(a){for(var b=a.bubbleElement;b.firstChild;)b.removeChild(b.firstChild);var c=a.bubbleElement.ownerDocument.createElement("div");c.id="bubble-message-"+a.id;c.textContent=a.message;a.bubbleElement.setAttribute("aria-labeledby",c.id);a.bubbleElement.setAttribute("role","alert");a.bubbleElement.setAttribute("aria-live","assertive");a.bubbleElement.appendChild(c);Ya(a.bubbleElement,!0);b=a.bubbleElement;a={top:a.targetRect.top-10+"px",left:a.targetRect.left+a.targetRect.width/2+"px"};for(var d in a)Xa(b,
d,a[d])};var Mb,Nb,Ob=0;function Q(a){this.form=a;this.ampdoc=D(a);this.mutator=I(a);this.root=this.ampdoc.getRootNode();this.ba=null}l=Q.prototype;l.report=function(){};l.onBlur=function(){};l.onInput=function(){};l.inputs=function(){return this.form.querySelectorAll("input,select,textarea")};
l.checkInputValidity=function(a){if("TEXTAREA"===a.tagName&&a.hasAttribute("pattern")&&(a.checkValidity()||"Please match the requested format."===a.validationMessage)){var b=a.getAttribute("pattern"),c=new RegExp("^"+b+"$","m"),d=c.test(a.value);a.setCustomValidity(d?"":"Please match the requested format.")}return a.checkValidity()};l.checkFormValidity=function(a){Pb(this,a);return a.checkValidity()};l.reportFormValidity=function(a){Pb(this,a);return a.reportValidity()};
function Pb(a,b){H(b.elements,function(b){"TEXTAREA"==b.tagName&&a.checkInputValidity(b)})}l.fireValidityEventIfNecessary=function(){var a=this.ba;this.ba=this.checkFormValidity(this.form);if(a!==this.ba){var b=ab(this.form.ownerDocument.defaultView,this.ba?"valid":"invalid",null,{bubbles:!0});this.form.dispatchEvent(b)}};function Qb(){Q.apply(this,arguments)}n(Qb,Q);Qb.prototype.report=function(){this.reportFormValidity(this.form);this.fireValidityEventIfNecessary()};
function S(a){Q.call(this,a);var b="i-amphtml-validation-bubble-"+Ob++;this.T=new Ib(this.ampdoc,b)}n(S,Q);S.prototype.report=function(){for(var a=this.inputs(),b=0;b<a.length;b++)if(!this.checkInputValidity(a[b])){a[b].focus();this.T.show(a[b],a[b].validationMessage);break}this.fireValidityEventIfNecessary()};S.prototype.onBlur=function(a){"submit"!=a.target.type&&this.T.hide()};
S.prototype.onInput=function(a){a=a.target;this.T.isActiveOn(a)&&(this.checkInputValidity(a)?(a.removeAttribute("aria-invalid"),this.T.hide()):(a.setAttribute("aria-invalid","true"),this.T.show(a,a.validationMessage)))};function T(a){Q.call(this,a);this.Oa=this.form.id?this.form.id:String(Date.now()+Math.floor(100*Math.random()));this.Ea=0}n(T,Q);l=T.prototype;l.reportInput=function(a){var b=Rb(a);b&&this.showValidationFor(a,b)};l.hideAllValidations=function(){for(var a=this.inputs(),b=0;b<a.length;b++)this.hideValidationFor(a[b])};
l.getValidationFor=function(a,b){if(!a.id)return null;var c=b;var d=a.validationMessage;c="TEXTAREA"===a.tagName&&"customError"===c&&"Please match the requested format."===d?"patternMismatch":c;d="__AMP_VALIDATION_"+c;d in a||(a[d]=this.root.querySelector("[visible-when-invalid="+c+"][validation-for="+(a.id+"]")));return a[d]};
l.showValidationFor=function(a,b){var c=this.getValidationFor(a,b);if(c){c.textContent.trim()||(c.textContent=a.validationMessage);a.__AMP_VISIBLE_VALIDATION=c;var d=c.getAttribute("id");d||(d="i-amphtml-aria-desc-"+this.Oa+"-"+this.Ea++,c.setAttribute("id",d));a.setAttribute("aria-invalid","true");a.setAttribute("aria-describedby",d);this.mutator.mutateElement(c,function(){return c.classList.add("visible")})}};
l.hideValidationFor=function(a){var b=this.getVisibleValidationFor(a);b&&(delete a.__AMP_VISIBLE_VALIDATION,a.removeAttribute("aria-invalid"),a.removeAttribute("aria-describedby"),this.mutator.mutateElement(b,function(){return b.classList.remove("visible")}))};l.getVisibleValidationFor=function(a){return a.__AMP_VISIBLE_VALIDATION};l.shouldValidateOnInteraction=function(){throw Error("Not Implemented");};
l.onInteraction=function(a){a=a.target;var b=!!a.checkValidity&&this.shouldValidateOnInteraction(a);this.hideValidationFor(a);b&&!this.checkInputValidity(a)&&this.reportInput(a)};l.onBlur=function(a){this.onInteraction(a)};l.onInput=function(a){this.onInteraction(a)};function Sb(){T.apply(this,arguments)}n(Sb,T);Sb.prototype.report=function(){this.hideAllValidations();for(var a=this.inputs(),b=0;b<a.length;b++)if(!this.checkInputValidity(a[b])){this.reportInput(a[b]);a[b].focus();break}this.fireValidityEventIfNecessary()};
Sb.prototype.shouldValidateOnInteraction=function(a){return!!this.getVisibleValidationFor(a)};function U(){T.apply(this,arguments)}n(U,T);U.prototype.report=function(){this.hideAllValidations();for(var a=null,b=this.inputs(),c=0;c<b.length;c++)this.checkInputValidity(b[c])||(a=a||b[c],this.reportInput(b[c]));a&&a.focus();this.fireValidityEventIfNecessary()};U.prototype.shouldValidateOnInteraction=function(a){return!!this.getVisibleValidationFor(a)};function Tb(){T.apply(this,arguments)}n(Tb,T);
Tb.prototype.shouldValidateOnInteraction=function(){return!0};Tb.prototype.onInteraction=function(a){T.prototype.onInteraction.call(this,a);this.fireValidityEventIfNecessary()};function Ub(){U.apply(this,arguments)}n(Ub,U);Ub.prototype.shouldValidateOnInteraction=function(){return!0};Ub.prototype.onInteraction=function(a){U.prototype.onInteraction.call(this,a);this.fireValidityEventIfNecessary()};
function Vb(a){var b=a.getAttribute("custom-validation-reporting");switch(b){case "as-you-go":return new Tb(a);case "show-all-on-submit":return new U(a);case "interact-and-submit":return new Ub(a);case "show-first-on-submit":return new Sb(a)}a.ownerDocument&&void 0===Mb&&(Mb=!!document.createElement("form").reportValidity);return Mb?new Qb(a):new S(a)}
function Rb(a){var b=["badInput"];for(c in a.validity)b.includes(c)||b.push(c);var c=b.filter(function(b){return!0===a.validity[b]});return c.length?c[0]:null};function Wb(a){var b=a.ownerDocument.defaultView;b.FormProxy||(b.FormProxy=Xb(b));var c=b.FormProxy,d=new c(a);"action"in d||Yb(a,d);a.$p=d}
function Xb(a){function b(a){this.h=a}var c=b.prototype,d=a.Object,e=d.prototype,f=[a.HTMLFormElement,a.EventTarget],g=f.reduce(function(a,b){for(b=b&&b.prototype;b&&b!==e&&!(0<=a.indexOf(b));)a.push(b),b=d.getPrototypeOf(b);return a},[]);g.forEach(function(b){var d={},f;for(f in b){d.w=a.Object.getOwnPropertyDescriptor(b,f);if(d.w&&f.toUpperCase()!=f&&!ua(f,"on")&&!e.hasOwnProperty.call(c,f))if("function"==typeof d.w.value)d.ea=d.w.value,c[f]=function(a){return function(){return a.ea.apply(this.h,
arguments)}}(d);else{var g={};d.w.get&&(g.get=function(a){return function(){return a.w.get.call(this.h)}}(d));d.w.set&&(g.set=function(a){return function(b){return a.w.set.call(this.h,b)}}(d));a.Object.defineProperty(c,f,g)}d={ea:d.ea,w:d.w}}});return b}
function Yb(a,b){var c=a.ownerDocument.defaultView.HTMLFormElement.prototype.cloneNode.call(a,!1),d={},e;for(e in c){d.l=e;if(!(d.l in b||d.l.toUpperCase()==d.l||ua(d.l,"on"))){d.m=Zb[d.l];var f=a[d.l];if(d.m)if(d.m.access==V){d.N=void 0;if(f&&f.nodeType){var g=c=f,h=g.nextSibling;g=g.parentNode;g.removeChild(c);try{d.N=a[d.l]}finally{g.insertBefore(c,h)}}else d.N=f;Object.defineProperty(b,d.l,{get:function(a){return function(){return a.N}}(d)})}else d.m.access==W&&(d.O=d.m.attr||d.l,Object.defineProperty(b,
d.l,{get:function(c){return function(){var d=b.getAttribute(c.O);return null==d&&void 0!==c.m.def?c.m.def:c.m.type==$b?"true"===d:c.m.type==ac?null!=d:c.m.type==bc?(d=d||"",B(a,"url").parse(d).href):d}}(d),set:function(a){return function(c){a.m.type==ac&&(c=c?"":null);null!=c?b.setAttribute(a.O,c):b.removeAttribute(a.O)}}(d)}));else Object.defineProperty(b,d.l,{get:function(b){return function(){return a[b.l]}}(d),set:function(b){return function(c){a[b.l]=c}}(d)})}d={N:d.N,O:d.O,m:d.m,l:d.l}}}
var W=1,V=2,bc=1,$b=2,ac=3,Zb={acceptCharset:{access:W,attr:"accept-charset"},accessKey:{access:W,attr:"accesskey"},action:{access:W,type:bc},attributes:{access:V},autocomplete:{access:W,def:"on"},children:{access:V},dataset:{access:V},dir:{access:W},draggable:{access:W,type:$b,def:!1},elements:{access:V},encoding:{access:V},enctype:{access:W},hidden:{access:W,type:ac,def:!1},id:{access:W,def:""},lang:{access:W},localName:{access:V},method:{access:W,def:"get"},name:{access:W},noValidate:{access:W,
attr:"novalidate",type:ac,def:!1},prefix:{access:V},spellcheck:{access:W},style:{access:V},target:{access:W,def:""},title:{access:W},translate:{access:W}};function cc(a,b){var c='form.amp-form-submit-error [submit-error],form.amp-form-submit-success [submit-success],form.amp-form-submitting [submitting]{display:block}textarea[autoexpand]:not(.i-amphtml-textarea-max){overflow:hidden!important}.i-amphtml-textarea-clone{visibility:hidden;position:absolute;top:-9999px;left:-9999px;height:0!important}.i-amphtml-validation-bubble{transform:translate(-50%,-100%);background-color:#fff;box-shadow:0 5px 15px 0 rgba(0,0,0,0.5);max-width:200px;position:absolute;display:block;box-sizing:border-box;padding:10px;border-radius:5px}.i-amphtml-validation-bubble:after{content:" ";position:absolute;bottom:-8px;left:30px;width:0;height:0;border-left:8px solid transparent;border-right:8px solid transparent;border-top:8px solid #fff}[visible-when-invalid]{color:red}\n/*# sourceURL=/extensions/amp-form/0.1/amp-form.css*/',
d=!1,e="amp-form",f=a.getHeadNode(),g=dc(f,ec(f,c),d||!1,e||null);if(b){var h=a.getRootNode();if(fc(h,g))b(g);else var k=setInterval(function(){fc(h,g)&&(clearInterval(k),b(g))},4)}}
function dc(a,b,c,d){var e=a.__AMP_CSS_SM;e||(e=a.__AMP_CSS_SM=v());var f=!c&&d&&"amp-custom"!=d&&"amp-keyframes"!=d,g=c?"amp-runtime":f?"amp-extension="+d:null;if(g){var h=jc(a,e,g);if(h)return h.textContent!==b&&(h.textContent=b),h}var k=(a.ownerDocument||a).createElement("style");k.textContent=b;var m=null;c?k.setAttribute("amp-runtime",""):f?(k.setAttribute("amp-extension",d||""),m=jc(a,e,"amp-runtime")):(d&&k.setAttribute(d,""),m=a.lastChild);b=m;a.insertBefore(k,b?b.nextSibling:a.firstChild);
g&&(e[g]=k);return k}function jc(a,b,c){return b[c]?b[c]:(a=a.querySelector("style["+c+"]"))?b[c]=a:null}function ec(a,b){return(a=a.__AMP_CSS_TR)?a(b):b}function fc(a,b){var c=a.styleSheets;for(a=0;a<c.length;a++){var d=c[a];if(d.ownerNode==b)return!0}return!1};function kc(a){var b=["\u26a14email","amp4email"],c=a.documentElement,d=b.some(function(a){return c.hasAttribute(a)});return d};function lc(a,b,c){Ua(a,"amp-analytics-instrumentation","amp-analytics").then(function(d){d&&d.triggerEventForTarget(a,b,c)})};function mc(a,b){try{return JSON.parse(a)}catch(c){return b&&b(c),null}};var nc=["amp-selector"];
function oc(a,b){var c=this;try{Wb(a)}catch(f){t().error("amp-form","form proxy failed to install",f)}a.__AMP_FORM=this;this.ka=b;this.j=a.ownerDocument.defaultView;this.Na=F(this.j,"timer");this.ya=B(a,"url-replace");this.ja=null;this.h=a;this.Da=D(this.h);this.A=F(this.j,"templates");this.pa=F(this.j,"xhr");this.Y=B(this.h,"action");this.sa=I(this.h);this.L=G(this.h,"viewer");this.R=new P(this.L,this.A);this.H=(this.h.getAttribute("method")||"GET").toUpperCase();this.Ma=this.h.getAttribute("target");
this.M=pc(this,"action-xhr");this.Sa=pc(this,"verify-xhr");this.xa=!this.h.hasAttribute("novalidate");this.h.setAttribute("novalidate","");this.xa||this.h.setAttribute("amp-novalidate","");this.h.classList.add("i-amphtml-form");this.I="initial";b=this.h.elements;for(var d=0;d<b.length;d++){var e=b[d].name;u("__amp_source_origin"!=e&&"__amp_form_verify"!=e,"Illegal input name, %s found: %s",e,b[d])}this.$=new Bb(this.h,this.j);this.U=Vb(this.h);this.Pa=rb(this.h,function(){return qc(c)});this.Y.installActionHandler(this.h,
this.Ca.bind(this));this.la();rc(this);sc(this);this.qa=this.Ja=this.Ra=null;Na(E(a),"form-submit-service").then(function(a){c.qa=a})}function pc(a,b){var c=a.h.getAttribute(b);if(c){var d=B(a.h,"url");d.assertHttpsUrl(c,a.h,b);u(!d.isProxyOrigin(c),"form %s should not be on AMP CDN: %s",b,a.h)}return c}l=oc.prototype;l.getXssiPrefix=function(){return this.h.getAttribute("xssi-prefix")};
l.requestForFormFetch=function(a,b,c,d){var e="GET"==b||"HEAD"==b;if(e){tc(this);var f=K(this.h);d&&d.forEach(function(a){delete f[a]});c&&ta(f,c);var g=Da(a,Ea(f))}else{g=a;var h=yb(this.j,this.h);d&&d.forEach(function(a){h.delete(a)});for(var k in c)h.append(k,c[k])}var m={xhrUrl:g,fetchOpt:w({body:h,method:b,credentials:"include",headers:w({Accept:"application/json"})})};return Gb(this.h).then(function(a){a&&(u("POST"==m.fetchOpt.method,"Cannot attach auth token with GET request."),h.append("ampViewerAuthToken",
a));return m})};l.setXhrAction=function(a){this.M=a};l.Ca=function(a){var b=this;if(!a.satisfiesTrust(2))return null;if("submit"==a.method)return uc(this).then(function(){var c=a;return"submitting"!=b.I&&vc(b)?wc(b,c.trust,null):Promise.resolve(null)});"clear"===a.method&&xc(this);return null};function uc(a){if(a.ja)return a.ja;var b=a.h.querySelectorAll(nc.join(",")),c=la(b).map(function(a){return a.whenBuilt()});return a.ja=yc(a,c,2E3)}
l.la=function(){var a=this;this.Da.whenNextVisible().then(function(){var b=a.h.querySelector("[autofocus]");if(b)try{b.focus()}catch(c){}});this.h.addEventListener("submit",this.ra.bind(this),!0);this.h.addEventListener("blur",function(b){zc(b.target);a.U.onBlur(b)},!0);this.h.addEventListener("amp:form-value-change",function(b){zc(b.target);a.U.onInput(b)},!0);this.R.isEnabled()||this.h.addEventListener("change",function(b){a.Pa.onCommit().then(function(c){var d=c,e=d.updatedElements,f=d.errors;
e.forEach(zc);a.U.onBlur(b);"verifying"===a.I&&(f.length?(X(a,"verify-error"),Y(a,w({verifyErrors:f})).then(function(){Ac(a,"verify-error",f,2)})):X(a,"initial"))})});this.h.addEventListener("input",function(b){zc(b.target);a.U.onInput(b)})};function rc(a){Ua(a.h,"inputmask","amp-inputmask").then(function(a){a&&a.install()})}
function Bc(a,b){Cc(a,"Form analytics not supported");var c=w({}),d=K(a.h),e;for(e in d)Object.prototype.hasOwnProperty.call(d,e)&&(c["formFields["+e+"]"]=d[e].join(","));c.formId=a.h.id;lc(a.h,b,c)}
function xc(a){a.h.reset();X(a,"initial");a.h.classList.remove("user-valid");a.h.classList.remove("user-invalid");var b=a.h.querySelectorAll(".user-valid, .user-invalid");H(b,function(a){a.classList.remove("user-valid");a.classList.remove("user-invalid")});var c=a.h.querySelectorAll(".visible[validation-for]");H(c,function(a){a.classList.remove("visible")});Dc(a.h)}
l.ra=function(a){if("submitting"==this.I||!vc(this))return a.stopImmediatePropagation(),a.preventDefault(),Promise.resolve(null);(this.M||"POST"==this.H)&&a.preventDefault();return wc(this,3,a)};
function wc(a,b,c){try{var d={form:a.h,actionXhrMutator:a.setXhrAction.bind(a)};a.qa.fire(d)}catch(m){t().error("amp-form","Form submit service failed: %s",m)}var e=Ec(a),f=a.h.getElementsByClassName("i-amphtml-async-input");a.$.onSubmitting();if(!a.M&&"GET"==a.H){Cc(a,"Non-XHR GETs not supported.");tc(a);if(0===f.length){for(d=0;d<e.length;d++)a.ya.expandInputValueSync(e[d]);var g=!c;Fc(a,g);a.$.onSubmitSuccess();return Promise.resolve()}c&&c.preventDefault()}X(a,"submitting");var h=[],k=[];k.push(Gc(a,
e));H(f,function(b){var c=Hc(a,b);b.classList.contains("i-async-require-action")?h.push(c):k.push(c)});return Promise.all(h).then(function(){return yc(a,k,1E4).then(function(){if(a.M)var c=Ic(a,b);else"POST"==a.H?u(!1,"Only XHR based (via action-xhr attribute) submissions are supported for POST requests. %s",a.h):"GET"==a.H&&Fc(a,!0),c=Promise.resolve();return c},function(c){return Jc(a,c,b)})},function(c){return Jc(a,c,b)})}
function Jc(a,b,c){var d={};b&&b.message&&(d.error=b.message);return Kc(a,b,d,c)}function Ec(a){return a.h.querySelectorAll('[type="hidden"][data-amp-replace]')}function qc(a){if("submitting"===a.I)return Promise.resolve();X(a,"verifying");Ac(a,"verify",null,3);return Gc(a,Ec(a)).then(function(){return Lc(a)})}function Ic(a,b){if(a.R.isEnabled())var c=Mc(a,b);else Nc(a,b),c=a.aa(a.M,a.H).then(function(c){return Oc(a,c,b)},function(c){return Pc(a,c,b)});return c}
function Mc(a,b){var c,d=K(a.h);return Y(a,d).then(function(){return a.Y.trigger(a.h,"submit",null,b)}).then(function(){return a.requestForFormFetch(a.M,a.H)}).then(function(b){var d=c=b,e=c.fetchOpt||{};var h=e.method;void 0===h?h="GET":(h=h.toUpperCase(),Fb.includes(h));e.method=h;e.headers=e.headers||w({});d.fetchOpt=e;d=c;h=c.xhrUrl;e=(e=c.fetchOpt)||{};var k=a.j;k=k.origin||y(k.location.href).origin;h=y(h).origin;k==h&&(e.headers=e.headers||{},e.headers["AMP-Same-Origin"]="true");d.fetchOpt=
e;d=c;e=c.xhrUrl;if(!1!==c.fetchOpt.ampCors){h=a.j;k=y(e);k=ja(k.search);u(!("__amp_source_origin"in k),"Source origin is not allowed in %s",e);h=h.location.href;"string"==typeof h&&(h=y(h));if(Fa(h)){k=h.pathname.split("/");u(va[k[1]],"Unknown path prefix in url %s",h.href);var m=k[2],z="s"==m?"https://"+decodeURIComponent(k[3]):"http://"+decodeURIComponent(m);u(0<z.indexOf("."),"Expected a . in origin %s",z);k.splice(1,"s"==m?3:2);k=z+k.join("/");m=(m=h.search)&&"?"!=m?(m=m.replace(ya,"").replace(za,
"").replace(Aa,"").replace(Ba,"").replace(Ca,"").replace(/^[?&]/,""))?"?"+m:"":"";h=k+m+(h.hash||"")}else h=h.href;h=y(h).origin;h=encodeURIComponent("__amp_source_origin")+"="+encodeURIComponent(h);e=Da(e,h,void 0)}d.xhrUrl=e;return a.R.ssr(a.h,c,Qc(a))}).then(function(c){return Rc(a,c,b)},function(c){var d={};c&&c.message&&(d.error=c.message);return Kc(a,c,d,b)})}
function Qc(a){var b,c=a.h.querySelector("[submit-success]");c&&(b=a.A.maybeFindTemplate(c));var d,e=a.h.querySelector("[submit-error]");e&&(d=a.A.maybeFindTemplate(e));return{successTemplate:b,errorTemplate:d}}function Rc(a,b,c){var d=b.init,e=mc(b.body,function(a){return r().error("amp-form","Failed to parse response JSON: %s",a)});return d&&(d=d.status,300<=d)?Kc(a,d,b,c,e):Sc(a,b,c,e)}
function Nc(a,b){Bc(a,"amp-form-submit");var c=K(a.h);Y(a,c).then(function(){a.Y.trigger(a.h,"submit",null,b)})}function Gc(a,b){for(var c=[],d=0;d<b.length;d++)c.push(a.ya.expandInputValueAsync(b[d]));return yc(a,c,100)}
function Hc(a,b){return b.getImpl().then(function(a){return a.getValue()}).then(function(c){var d=b.getAttribute("name");d=a.h.querySelector("input[name="+String(d).replace(Pa,Qa)+"]");if(!d){d=w({name:b.getAttribute("name"),hidden:"true"});var e=a.j.document.createElement("input"),f;for(f in d)e.setAttribute(f,d[f]);d=e}d.setAttribute("value",c);a.h.appendChild(d)})}
function Lc(a){var b=la(a.h.querySelectorAll("["+"no-verify".replace(Pa,Qa)+"]")),c=b.map(function(a){return a.name||a.id}),d={};return a.aa(a.Sa,a.H,(d.__amp_form_verify=!0,d),c)}l.aa=function(a,b,c,d){var e=this;Cc(this,"XHRs should be proxied.");return this.requestForFormFetch(a,b,c,d).then(function(a){return e.pa.fetch(a.xhrUrl,a.fetchOpt)})};
function Tc(a,b){2>=b&&t().expectedError("amp-form","Recursive form submissions are scheduled to be deprecated by 1/1/2020. See https://github.com/ampproject/amphtml/issues/24894.");return(a=a.h.ownerDocument)&&kc(a)?b-1:b}function Oc(a,b,c){return a.pa.xssiJson(b,a.getXssiPrefix()).then(function(b){return Sc(a,b,c)},function(a){return r().error("amp-form","Failed to parse response JSON: %s",a)}).then(function(){Bc(a,"amp-form-submit-success");Uc(a,b)})}
function Sc(a,b,c,d){X(a,"submit-success");return qa(function(){Y(a,b||{}).then(function(){var e=Tc(a,c);Ac(a,"submit-success",void 0===d?b:d,e);a.$.onSubmitSuccess()})})}function Pc(a,b,c){return(b&&b.response?a.pa.xssiJson(b.response,a.getXssiPrefix()).catch(function(){return null}):Promise.resolve(null)).then(function(d){Bc(a,"amp-form-submit-error");Kc(a,b,d,c);Uc(a,b.response)})}
function Kc(a,b,c,d,e){X(a,"submit-error");r().error("amp-form","Form submission failed: %s",b);return qa(function(){Y(a,c).then(function(){var b=Tc(a,d);Ac(a,"submit-error",void 0===e?c:e,b);a.$.onSubmitError()})})}function Fc(a,b){Bc(a,"amp-form-submit");b&&a.h.submit();X(a,"initial")}function Cc(a,b){var c=a.R.isEnabled();u(!1===c,"[amp-form]: viewerRenderTemplate | %s",b)}
function tc(a){var b=a.h.querySelectorAll("input[type=password],input[type=file]");u(0==b.length,"input[type=password] or input[type=file] may only appear in form[method=post]")}function vc(a){void 0===Nb&&(Nb=!!a.j.document.createElement("input").checkValidity);if(Nb){var b=Vc(a.h);if(a.xa)return a.U.report(),b}return!0}
function Uc(a,b){Cc(a,"Redirects not supported.");if(b&&b.headers){var c=b.headers.get("AMP-Redirect-To");if(c){b=a.h.ownerDocument;u(!(b&&kc(b)),"Redirects not supported in AMP4Email.",a.h);u("_blank"!=a.Ma,"Redirecting to target=_blank using AMP-Redirect-To is currently not supported, use target=_top instead. %s",a.h);try{var d=B(a.h,"url");d.assertAbsoluteHttpOrHttpsUrl(c);d.assertHttpsUrl(c,"AMP-Redirect-To","Url")}catch(e){u(!1,"The `AMP-Redirect-To` header value must be an absolute URL starting with https://. Found %s",
c)}G(a.h,"navigation").navigateTo(a.j,c,"AMP-Redirect-To")}}}function Ac(a,b,c,d){c=ab(a.j,"amp-form."+b,w({response:c}));a.Y.trigger(a.h,b,c,d)}function yc(a,b,c){return Promise.race([Promise.all(b),a.Na.promise(c)])}
function X(a,b){var c=a.I;a.h.classList.remove("amp-form-"+c);a.h.classList.add("amp-form-"+b);var d=a.h.querySelector("["+c+"]");if(d){/^[\w-]+$/.test("i-amphtml-rendered");if(void 0!==Ra)var e=Ra;else{try{var f=d.ownerDocument,g=f.createElement("div"),h=f.createElement("div");g.appendChild(h);e=g.querySelector(":scope div")===h}catch(k){e=!1}e=Ra=e}e?d=d.querySelector("> [i-amphtml-rendered]".replace(/^|,/g,"$&:scope ")):(d.classList.add("i-amphtml-scoped"),e="> [i-amphtml-rendered]".replace(/^|,/g,
"$&.i-amphtml-scoped "),e=d.querySelectorAll(e),d.classList.remove("i-amphtml-scoped"),d=void 0===e[0]?null:e[0]);d&&d.parentElement&&d.parentElement.removeChild(d)}a.I=b}
function Y(a,b){Array.isArray(b)&&(b={},r().warn("amp-form","Unexpected data type: "+b+". Expected non JSON array."));var c=a.h.querySelector("["+a.I+"]"),d=Promise.resolve();if(c){var e="rendered-message-"+a.ka;c.setAttribute("role","alert");c.setAttribute("aria-labeledby",e);c.setAttribute("aria-live","assertive");a.A.hasTemplate(c)?d=a.R.applySsrOrCsrTemplate(c,b).then(function(b){b.id=e;b.setAttribute("i-amphtml-rendered","");return a.sa.mutateElement(c,function(){c.appendChild(b);var d=ab(a.j,
"amp:dom-update",null,{bubbles:!0});c.dispatchEvent(d)})}):a.sa.mutateElement(c,function(){})}return d}
function sc(a){if(!Fa(a.j.location)&&a.h.hasAttribute("data-initialize-from-url")){var b=["SELECT","TEXTAREA"],c="color date datetime-local email hidden month number range search tel text time url week".split(" "),d=["checkbox","radio"],e=function(a,e){if(!a.hasAttribute("data-amp-replace")&&a.hasAttribute("data-allow-initialization")){e=f[e]||"";var g=a.getAttribute("type")||"text",h=a.tagName;"INPUT"===h?c.includes(g.toLocaleLowerCase())?a.value!==e&&(a.value=e):d.includes(g)&&(e=a.value===e,a.checked!==
e&&(a.checked=e)):b.includes(h)&&a.value!==e&&(a.value=e)}},f=ja(a.j.location.search);Object.keys(f).forEach(function(b){var c=a.h.elements[b];c&&(c.nodeType===Node.ELEMENT_NODE?e(c,b):c.length&&H(c,function(a){return e(a,b)}))})}}l.Ta=function(){return this.Ja};l.Va=function(){return this.Ra};function Vc(a){var b=a.querySelectorAll("input,select,textarea,fieldset");H(b,function(a){return Z(a)});return Z(a)}
function Dc(a){var b=document.createElement("input"),c={},d;for(d in b.validity){c.X=d;var e=a.querySelectorAll("."+String(c.X).replace(Pa,Qa));H(e,function(a){return function(b){b.classList.remove(a.X)}}(c));c={X:c.X}}}
function Z(a,b){b=void 0===b?!1:b;if(!a.checkValidity)return!0;var c=!1,d=a.classList.contains("user-valid")?"valid":a.classList.contains("user-invalid")?"invalid":"none",e=a.checkValidity();"valid"!=d&&e?(a.classList.add("user-valid"),a.classList.remove("user-invalid"),c="invalid"==d):"invalid"==d||e||(a.classList.add("user-invalid"),a.classList.remove("user-valid"),c=!0);if(a.validity)for(var f in a.validity)a.classList.toggle(f,a.validity[f]);if(b&&c){f=Ta(a);for(var g=0;g<f.length;g++)Z(f[g]);
a.form&&Z(a.form)}return e}function zc(a){Z(a,!0)}function Wc(a){this.Qa=Xc(a).then(function(){return Yc(a)})}Wc.prototype.whenInitialized=function(){return this.Qa};function Xc(a){var b=new pa;cc(a,b.resolve);return b.promise}function Yc(a){return a.whenReady().then(function(){var b=a.getRootNode();Zc(b.querySelectorAll("form"));lb(a);$c(b);ad(b)})}function Zc(a){a&&H(a,function(a,c){var b=a.__AMP_FORM||null;b||new oc(a,"amp-form-"+c)})}
function $c(a){a.addEventListener("amp:dom-update",function(){Zc(a.querySelectorAll("form"))})}function ad(a){a.addEventListener("keydown",function(a){if(!a.defaultPrevented&&"Enter"==a.key&&(a.ctrlKey||a.metaKey)&&"TEXTAREA"===a.target.tagName){var b=a.target.form,d=b?b.__AMP_FORM||null:null;d&&(d.ra(a),a.preventDefault())}})}(function(a){a.registerServiceForDoc("form-submit-service",Eb);a.registerServiceForDoc("amp-form",Wc)})(self.AMP);
})});

//# sourceMappingURL=amp-form-0.1.js.map
