(self.AMP=self.AMP||[]).push({n:"amp-ad-exit",v:"2004071640410",f:(function(AMP,_){
var k,aa="function"==typeof Object.create?Object.create:function(a){function b(){}b.prototype=a;return new b},l;if("function"==typeof Object.setPrototypeOf)l=Object.setPrototypeOf;else{var m;a:{var ba={a:!0},n={};try{n.__proto__=ba;m=n.a;break a}catch(a){}m=!1}l=m?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}var r=l;
function t(a,b){a.prototype=aa(b.prototype);a.prototype.constructor=a;if(r)r(a,b);else for(var c in b)if("prototype"!=c)if(Object.defineProperties){var e=Object.getOwnPropertyDescriptor(b,c);e&&Object.defineProperty(a,c,e)}else a[c]=b[c];a.T=b.prototype};function u(a,b){b=void 0===b?"":b;try{return decodeURIComponent(a)}catch(c){return b}};var ca=/(?:^[#?]?|&)([^=&]+)(?:=([^&]*))?/g;function v(a){var b=Object.create(null);if(!a)return b;for(var c;c=ca.exec(a);){var e=u(c[1],c[1]),d=c[2]?u(c[2].replace(/\+/g," "),c[2]):"";b[e]=d}return b};var w="";
function ha(){var a,b=a||self;if(b.__AMP_MODE)var c=b.__AMP_MODE;else{c=b;var e=self.AMP_CONFIG||{},d=!!e.test||!1,f=v(c.location.originalHash||c.location.hash);e=e.spt;var h=v(c.location.search);w||(w=c.AMP_CONFIG&&c.AMP_CONFIG.v?c.AMP_CONFIG.v:"012004071640410");c={localDev:!1,development:!!(0<=["1","actions","amp","amp4ads","amp4email"].indexOf(f.development)||c.AMP_DEV_MODE),examiner:"2"==f.development,esm:!1,geoOverride:f["amp-geo"],minified:!0,lite:void 0!=h.amp_lite,test:d,log:f.log,version:"2004071640410",
rtvVersion:w,singlePassType:e};c=b.__AMP_MODE=c}return c};var ia=Object.prototype.toString;var x=self.AMP_CONFIG||{},ja=("string"==typeof x.cdnProxyRegex?new RegExp(x.cdnProxyRegex):x.cdnProxyRegex)||/^https:\/\/([a-zA-Z0-9_-]+\.)?cdn\.ampproject\.org$/;function y(a){if(self.document&&self.document.head&&(!self.location||!ja.test(self.location.origin))){var b=self.document.head.querySelector('meta[name="'+a+'"]');b&&b.getAttribute("content")}}x.cdnUrl||y("runtime-host");x.geoApiUrl||y("amp-geo-api");self.__AMP_LOG=self.__AMP_LOG||{user:null,dev:null,userForEmbed:null};var z=self.__AMP_LOG;function A(){if(!z.user)throw Error("failed to call initLogConstructor");return z.user}function B(){if(z.dev)return z.dev;throw Error("failed to call initLogConstructor");}function C(a,b,c,e){A().assert(a,b,c,e,void 0,void 0,void 0,void 0,void 0,void 0,void 0)};function D(a,b){this.name=a;this.type=b}D.prototype.filter=function(){};D.prototype.onLayoutMeasure=function(){};function ka(){var a,b;this.promise=new Promise(function(c,e){a=c;b=e});this.resolve=a;this.reject=b};var E=Object.prototype.hasOwnProperty;function F(){var a=100;this.N=a;this.D=this.H=0;this.o=Object.create(null)}F.prototype.has=function(a){return!!this.o[a]};F.prototype.get=function(a){var b=this.o[a];if(b)return b.access=++this.D,b.payload};F.prototype.put=function(a,b){this.has(a)||this.H++;this.o[a]={payload:b,access:this.D};if(!(this.H<=this.N)){B().warn("lru-cache","Trimming LRU cache");a=this.o;var c=this.D+1,e;for(e in a){var d=a[e].access;if(d<c){c=d;var f=e}}void 0!==f&&(delete a[f],this.H--)}};(function(a){return a||{}})({c:!0,v:!0,a:!0,ad:!0,action:!0});var G,H;
function I(a){var b;G||(G=self.document.createElement("a"),H=self.__AMP_URL_CACHE||(self.__AMP_URL_CACHE=new F));var c=b?null:H,e=G;if(c&&c.has(a))a=c.get(a);else{e.href=a;e.protocol||(e.href=e.href);var d={href:e.href,protocol:e.protocol,host:e.host,hostname:e.hostname,port:"0"==e.port?"":e.port,pathname:e.pathname,search:e.search,hash:e.hash,origin:null};"/"!==d.pathname[0]&&(d.pathname="/"+d.pathname);if("http:"==d.protocol&&80==d.port||"https:"==d.protocol&&443==d.port)d.port="",d.host=d.hostname;
d.origin=e.origin&&"null"!=e.origin?e.origin:"data:"!=d.protocol&&d.host?d.protocol+"//"+d.host:d.href;c&&c.put(a,d);a=d}return a};function J(a,b){if(a.__AMP__EXPERIMENT_TOGGLES)var c=a.__AMP__EXPERIMENT_TOGGLES;else{a.__AMP__EXPERIMENT_TOGGLES=Object.create(null);c=a.__AMP__EXPERIMENT_TOGGLES;if(a.AMP_CONFIG)for(var e in a.AMP_CONFIG){var d=a.AMP_CONFIG[e];"number"===typeof d&&0<=d&&1>=d&&(c[e]=Math.random()<d)}if(a.AMP_CONFIG&&Array.isArray(a.AMP_CONFIG["allow-doc-opt-in"])&&0<a.AMP_CONFIG["allow-doc-opt-in"].length&&(e=a.AMP_CONFIG["allow-doc-opt-in"],d=a.document.head.querySelector('meta[name="amp-experiments-opt-in"]'))){d=
d.getAttribute("content").split(",");for(var f=0;f<d.length;f++)-1!=e.indexOf(d[f])&&(c[d[f]]=!0)}Object.assign(c,la(a));if(a.AMP_CONFIG&&Array.isArray(a.AMP_CONFIG["allow-url-opt-in"])&&0<a.AMP_CONFIG["allow-url-opt-in"].length)for(e=a.AMP_CONFIG["allow-url-opt-in"],a=v(a.location.originalHash||a.location.hash),d=0;d<e.length;d++)f=a["e-"+e[d]],"1"==f&&(c[e[d]]=!0),"0"==f&&(c[e[d]]=!1)}var h=c;return!!h[b]}
function la(a){var b="";try{"localStorage"in a&&(b=a.localStorage.getItem("amp-experiment-toggles"))}catch(d){B().warn("EXPERIMENTS","Failed to retrieve experiments from localStorage.")}var c=b?b.split(/\s*,\s*/g):[];a=Object.create(null);for(var e=0;e<c.length;e++)0!=c[e].length&&("-"==c[e][0]?a[c[e].substr(1)]=!1:a[c[e]]=!0);return a};var K={},L=(K["ampdoc-fie"]={isTrafficEligible:function(){return!0},branches:[["21065001"],["21065002"]]},K);function ma(a){var b=a.ownerDocument.defaultView,c=M(b),e=b!=c;var d=c;if(J(d,"ampdoc-fie")){d.__AMP_EXPERIMENT_BRANCHES=d.__AMP_EXPERIMENT_BRANCHES||{};for(var f in L)if(E.call(L,f)&&!E.call(d.__AMP_EXPERIMENT_BRANCHES,f))if(L[f].isTrafficEligible&&L[f].isTrafficEligible(d)){if(!d.__AMP_EXPERIMENT_BRANCHES[f]&&J(d,f)){var h=L[f].branches;d.__AMP_EXPERIMENT_BRANCHES[f]=h[Math.floor(Math.random()*h.length)]||null}}else d.__AMP_EXPERIMENT_BRANCHES[f]=null;d="21065002"===(d.__AMP_EXPERIMENT_BRANCHES?
d.__AMP_EXPERIMENT_BRANCHES["ampdoc-fie"]:null)}else d=!1;var g=d;e&&!g?a=N(b,"url-replace")?O(b,"url-replace"):null:(a=P(a),a=Q(a),a=N(a,"url-replace")?O(a,"url-replace"):null);return a}function M(a){return a.__AMP_TOP||(a.__AMP_TOP=a)}function P(a){if(a.nodeType){var b=(a.ownerDocument||a).defaultView;b=M(b);a=O(b,"ampdoc").getAmpDoc(a)}return a}function Q(a){a=P(a);return a.isSingleDoc()?a.win:a}
function O(a,b){N(a,b);var c=R(a);a=c[b];a.obj||(a.obj=new a.ctor(a.context),a.ctor=null,a.context=null,a.resolve&&a.resolve(a.obj));return a.obj}function na(a){var b;(b=R(a)["host-exit"])?b.promise?b=b.promise:(O(a,"host-exit"),b=b.promise=Promise.resolve(b.obj)):b=null;var c=b;if(c)return c;a=R(a);a["host-exit"]=oa();return a["host-exit"].promise}function R(a){var b=a.__AMP_SERVICES;b||(b=a.__AMP_SERVICES={});return b}
function N(a,b){a=a.__AMP_SERVICES&&a.__AMP_SERVICES[b];return!(!a||!a.ctor&&!a.obj)}function oa(){var a=new ka,b=a,c=b.promise,e=b.resolve;b=b.reject;c.catch(function(){});return{obj:null,promise:c,resolve:e,reject:b,context:null,ctor:null}};/*
 https://mths.be/cssescape v1.5.1 by @mathias | MIT license */
function S(a,b,c){var e;try{var d=a.open(b,c,e)}catch(h){B().error("DOM","Failed to open url on target: ",c,h)}if(!(c=d||"_top"==c)){c=e||"";var f;"number"!==typeof f&&(f=0);c=f+8>c.length?!1:-1!==c.indexOf("noopener",f)}c||a.open(b,"_top")};var T;function pa(a,b){var c=void 0,e=a,d=b;var f=function(a){try{return d(a)}catch(q){throw self.__AMP_REPORT_ERROR(q),q;}};var h=qa(),g=!1;c&&(g=c.capture);e.addEventListener("message",f,h?c:g);return function(){e&&e.removeEventListener("message",f,h?c:g);f=e=d=null}}function qa(){if(void 0!==T)return T;T=!1;try{var a={get capture(){T=!0}};self.addEventListener("test-options",null,a);self.removeEventListener("test-options",null,a)}catch(b){}return T};function ra(a,b){return pa(a,b)};var U={bg:"https://tpc.googlesyndication.com/b4a/b4a-runner.html",moat:"https://z.moatads.com/ampanalytics093284/iframe.html"};Object.assign({},U,{bg:"https://tpc.googlesyndication.com/b4a/experimental/b4a-runner.html"});function sa(a){C("object"==typeof a);if(a.filters){var b=a.filters,c=["clickDelay","clickLocation","inactiveElement"],e;for(e in b)C("object"==typeof b[e],"Filter specification '%s' is malformed",e),C(-1!=c.indexOf(b[e].type),"Supported filters: "+c.join(", "))}else a.filters={};if(a.transport){b=a.transport;for(var d in b)C("beacon"==d||"image"==d,"Unknown transport option: '"+d+"'"),C("boolean"==typeof b[d])}else a.transport={};d=a.targets;C("object"==typeof d,"'targets' must be an object");for(var f in d)ta(f,
d[f],a);return a}function ta(a,b,c){C("string"==typeof b.finalUrl,"finalUrl of target '%s' must be a string",a);b.filters&&b.filters.forEach(function(a){C(c.filters[a],"filter '%s' not defined",a)});if(b.vars){a=/^_[a-zA-Z0-9_-]+$/;for(var e in b.vars)C(a.test(e),"'%s' must match the pattern '%s'",e,a)}}function ua(a){return A().assertString(U[a],"Unknown or invalid vendor "+a+", note that vendor must use transport: iframe")};function V(a,b,c){D.call(this,a,b.type);C("clickDelay"==b.type&&"number"==typeof b.delay&&0<b.delay,"Invalid ClickDelay spec");this.spec=b;this.intervalStart=Date.now();b.startTimingEvent&&(c.performance&&c.performance.timing?void 0==c.performance.timing[b.startTimingEvent]?B().warn("amp-ad-exit","Invalid performance timing event type "+b.startTimingEvent+", falling back to now"):this.intervalStart=c.performance.timing[b.startTimingEvent]:B().warn("amp-ad-exit","Browser does not support performance timing, falling back to now"))}
t(V,D);V.prototype.filter=function(){return Date.now()-this.intervalStart>=this.spec.delay};function va(a){var b=1E3;return{type:"clickDelay",delay:b,startTimingEvent:a}};function W(a,b,c){D.call(this,a,b.type);C("clickLocation"==b.type&&("undefined"===typeof b.left||"number"===typeof b.left)&&("undefined"===typeof b.right||"number"===typeof b.right)&&("undefined"===typeof b.top||"number"===typeof b.top)&&("undefined"===typeof b.bottom||"number"===typeof b.bottom)&&("undefined"===typeof b.relativeTo||"string"===typeof b.relativeTo),"Invaid ClickLocation spec");this.O=b.left||0;this.P=b.right||0;this.S=b.top||0;this.M=b.bottom||0;this.G=b.relativeTo;this.J=c;this.h=
{top:0,right:0,bottom:0,left:0}}t(W,D);W.prototype.filter=function(a){return a.clientX>=this.h.left&&a.clientX<=this.h.right&&a.clientY>=this.h.top&&a.clientY<=this.h.bottom?!0:!1};
W.prototype.onLayoutMeasure=function(){var a=this;this.J.getVsync().measure(function(){var b=a.J.win;if(a.G){var c=b.document.querySelector(a.G);C(c,"relativeTo element "+a.G+" not found.");var e=c.getBoundingClientRect();a.h.left=e.left;a.h.top=e.top;a.h.bottom=e.bottom;a.h.right=e.right}else a.h.left=0,a.h.top=0,a.h.bottom=b.innerHeight,a.h.right=b.innerWidth;a.h.left+=a.O;a.h.top+=a.S;a.h.right-=a.P;a.h.bottom-=a.M})};function X(a,b){D.call(this,a,b.type);C("inactiveElement"==b.type&&"string"==typeof b.selector,"Invalid InactiveElementspec");this.R=b.selector}t(X,D);X.prototype.filter=function(a){a=a.target;var b=a.matches||a.webkitMatchesSelector||a.mozMatchesSelector||a.msMatchesSelector||a.oMatchesSelector;return!(b&&b.call(a,this.R))};function Y(a,b,c){switch(b.type){case "clickDelay":return new V(a,b,c.win);case "clickLocation":return new W(a,b,c);case "inactiveElement":return new X(a,b)}};function wa(a,b){try{a:{var c=(a.ownerDocument||a).defaultView,e=b||M(c);if(c&&c!=e&&M(c)==e)try{var d=c.frameElement;break a}catch(h){}d=null}var f=d.parentElement;if("AMP-AD"==f.nodeName)return String(f.getResourceId())}catch(h){}return null};function Z(a){a=AMP.BaseElement.call(this,a)||this;a.I={};a.K={};a.w=[];a.A={beacon:!0,image:!0};a.C={};a.registerAction("exit",a.exit.bind(a));a.registerAction("setVariable",a.setVariable.bind(a),1);a.L={};a.B=null;a.m=null;a.F={};return a}t(Z,AMP.BaseElement);k=Z.prototype;
k.exit=function(a){var b=this,c=a.args,e=a.event;C("variable"in c!="target"in c,"One and only one of 'target' and 'variable' must be specified");var d;"variable"in c?((d=this.K[c.variable])||(d=c["default"]),C(d,"Variable target not found, variable:'"+c.variable+"', default:'"+c["default"]+"'"),delete c["default"]):d=c.target;var f=this.I[d];C(f,"Exit target not found: '"+d+"'");C(e,"Unexpected null event");e.preventDefault();if(xa(this.w,e)&&xa(f.filters,e)){var h=ya(this,c,e,f);f.trackingUrls&&
f.trackingUrls.map(h).forEach(function(a){b.A.beacon&&b.win.navigator.sendBeacon&&b.win.navigator.sendBeacon(a,"")||!b.A.image||(b.win.document.createElement("img").src=a)});var g=h(f.finalUrl);if(P(this.getAmpDoc()).getHeadNode().querySelector("script[host-service]"))na(Q(this.getAmpDoc())).then(function(a){return a.openUrl(g)}).catch(function(a){a.fallback&&S(b.win,g,"_blank")});else{var p=f.behaviors&&f.behaviors.clickTarget&&"_top"==f.behaviors.clickTarget?"_top":"_blank";S(this.win,g,p)}}};
k.setVariable=function(a){a=a.args;var b=this.I[a.target];C(b,"Exit target not found: '"+a.target+"'");this.K[a.name]=a.target};
function ya(a,b,c,e){var d={CLICK_X:function(){return c.clientX},CLICK_Y:function(){return c.clientY}},f=ma(a.element),h={RANDOM:!0,CLICK_X:!0,CLICK_Y:!0};if(e.vars){var g={},p;for(p in e.vars)g.j=p,"_"==g.j[0]&&(g.l=e.vars[g.j],g.l&&(d[g.j]=function(c){return function(){if(c.l.iframeTransportSignal){var d=f.expandStringSync(c.l.iframeTransportSignal,{IFRAME_TRANSPORT_SIGNAL:function(b,c){if(!b||!c)return"";var d=a.L[b];if(d&&c in d)return d[c]}});if(c.l.iframeTransportSignal=="IFRAME_TRANSPORT_SIGNAL"+
d)B().error("amp-ad-exit","Invalid IFRAME_TRANSPORT_SIGNAL format:"+d+" (perhaps there is a space after a comma?)");else if(""!=d)return d}return c.j in b?b[c.j]:c.l.defaultValue}}(g),h[g.j]=!0)),g={l:g.l,j:g.j}}return function(a){return f.expandUrlSync(a,d,void 0,h)}}function xa(a,b){return a.every(function(a){var c=a.filter(b);A().info("amp-ad-exit","Filter '"+a.name+"': "+(c?"pass":"fail"));return c})}
k.buildCallback=function(){var a=this;this.element.setAttribute("aria-hidden","true");this.w.push(Y("minDelay",va(),this));this.w.push(Y("carouselBtns",{type:"inactiveElement",selector:".amp-carousel-button"},this));var b=this.element.children;C(1==b.length,"The tag should contain exactly one <script> child.");b=b[0];C("SCRIPT"==b.tagName&&b.hasAttribute("type")&&"APPLICATION/JSON"==b.getAttribute("type").toUpperCase(),'The amp-ad-exit config should be inside a <script> tag with type="application/json"');
try{var c=sa(JSON.parse(b.textContent));if("[object Object]"===ia.call(c.options)&&"string"===typeof c.options.startTimingEvent){var e=c.options.startTimingEvent;this.w.splice(0,1,Y("minDelay",va(c.options.startTimingEvent),this))}for(var d in c.filters){var f=c.filters[d];"clickDelay"==f.type&&(f.startTimingEvent=f.startTimingEvent||e);this.C[d]=Y(d,f,this)}for(var h in c.targets){var g=c.targets[h];this.I[h]={finalUrl:g.finalUrl,trackingUrls:g.trackingUrls||[],vars:g.vars||{},filters:(g.filters||
[]).map(function(b){return a.C[b]}).filter(function(a){return a}),behaviors:g.behaviors||{}};for(var p in g.vars)if(g.vars[p].iframeTransportSignal){var q=g.vars[p].iframeTransportSignal.match(/IFRAME_TRANSPORT_SIGNAL\(([^,]+)/);if(q&&!(2>q.length)){var fa=q[1],da=I(ua(fa)).origin;this.F[da]=this.F[da]||fa}}}this.A.beacon=!1!==c.transport.beacon;this.A.image=!1!==c.transport.image}catch(ea){throw this.user().error("amp-ad-exit","Invalid JSON config",ea),ea;}za(this)};k.resumeCallback=function(){za(this)};
k.unlayoutCallback=function(){this.B&&(this.B(),this.B=null);return AMP.BaseElement.prototype.unlayoutCallback.call(this)};
function za(a){"inabox"!=ha().runtime&&(a.m=a.m||wa(a.element,M(a.win)),a.m?a.B=ra(a.getAmpDoc().win,function(b){if(a.F[b.origin]){var c=b.data;if("string"==typeof c&&0==c.indexOf("amp-")&&-1!=c.indexOf("{")){var e=c.indexOf("{");try{var d=JSON.parse(c.substr(e))}catch(h){B().error("MESSAGING","Failed to parse message: "+c,h),d=null}}else d=null;var f=d;f&&"iframe-transport-response"==f.type&&(d=f,b=b.origin,C(d.message,"Received empty response from 3p analytics frame"),C(d.creativeId,"Received malformed message from 3p analytics frame: creativeId missing"),
C(d.vendor,"Received malformed message from 3p analytics frame: vendor missing"),c=I(ua(d.vendor)),C(c&&c.origin==b,"Invalid origin for vendor "+(d.vendor+": "+b)),f.creativeId==a.m&&(a.L[f.vendor]=f.message))}}):A().warn("amp-ad-exit","No friendly parent amp-ad element was found for amp-ad-exit; not in inabox case."))}k.isLayoutSupported=function(){return!0};k.onLayoutMeasure=function(){for(var a in this.C)this.C[a].onLayoutMeasure()};(function(a){a.registerElement("amp-ad-exit",Z)})(self.AMP);
})});

//# sourceMappingURL=amp-ad-exit-0.1.js.map
