(self.AMP=self.AMP||[]).push({n:"amp-form",v:"1904200955460",f:(function(AMP,_){
var l,aa="function"==typeof Object.create?Object.create:function(a){function b(){}b.prototype=a;return new b},ba;if("function"==typeof Object.setPrototypeOf)ba=Object.setPrototypeOf;else{var ca;a:{var da={a:!0},ea={};try{ea.__proto__=da;ca=ea.a;break a}catch(a){}ca=!1}ba=ca?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}var fa=ba;
function n(a,b){a.prototype=aa(b.prototype);a.prototype.constructor=a;if(fa)fa(a,b);else for(var c in b)if("prototype"!=c)if(Object.defineProperties){var d=Object.getOwnPropertyDescriptor(b,c);d&&Object.defineProperty(a,c,d)}else a[c]=b[c];a.Ia=b.prototype};function ha(){var a,b;this.promise=new Promise(function(c,d){a=c;b=d});this.resolve=a;this.reject=b}function ia(a){return new Promise(function(b){b(a())})}function ja(){var a,b,c;this.la=new Promise(function(a,d){b=a;c=d});this.Aa=b;this.za=c;this.ca=0;if(a)for(var d=0;d<a.length;d++)this.add(a[d])}ja.prototype.add=function(a){var b=this,c=++this.ca;Promise.resolve(a).then(function(a){b.ca===c&&b.Aa(a)},function(a){b.ca===c&&b.za(a)});return this.la};
ja.prototype.then=function(a,b){return this.la.then(a,b)};function ka(a,b){b=void 0===b?"":b;try{return decodeURIComponent(a)}catch(c){return b}};var la=/(?:^[#?]?|&)([^=&]+)(?:=([^&]*))?/g;function ma(a){var b=Object.create(null);if(!a)return b;for(var c;c=la.exec(a);){var d=ka(c[1],c[1]),e=c[2]?ka(c[2],c[2]):"";b[d]=e}return b};var na="";
function p(){var a,b=a||self;if(b.AMP_MODE)var c=b.AMP_MODE;else{c=b;var d=self.AMP_CONFIG||{},e=!!d.test||!1,f=ma(c.location.originalHash||c.location.hash);d=d.spt;var g=ma(c.location.search);na||(na=c.AMP_CONFIG&&c.AMP_CONFIG.v?c.AMP_CONFIG.v:"011904200955460");c=b.AMP_MODE={localDev:!1,development:!("1"!=f.development&&!c.AMP_DEV_MODE),examiner:"2"==f.development,filter:f.filter,geoOverride:f["amp-geo"],minified:!0,lite:void 0!=g.amp_lite,test:e,log:f.log,version:"1904200955460",rtvVersion:na,singlePassType:d}}return c}
;var oa=Object.prototype.toString;function pa(a){return a?Array.prototype.slice.call(a):[]}function qa(a){return"[object Object]"===oa.call(a)};self.log=self.log||{user:null,dev:null,userForEmbed:null};var q=self.log;function r(){if(!q.user)throw Error("failed to call initLogConstructor");return q.user}function t(){if(q.dev)return q.dev;throw Error("failed to call initLogConstructor");}function u(a,b,c,d){r().assert(a,b,c,d,void 0,void 0,void 0,void 0,void 0,void 0,void 0)};function v(a,b){var c,d=a.ownerDocument.defaultView,e=d!=(d.__AMP_TOP||d);if(e){if(ra(d,b)){var f=w(d,b);if(f)return f}if(!c)return null}a=x(a);a=y(a);return ra(a,b)?w(a,b):null}function z(a,b){a=a.__AMP_TOP||a;return w(a,b)}function A(a,b){var c=x(a);c=y(c);return w(c,b)}function sa(a,b){return ta(y(a),b)}function x(a){return a.nodeType?z((a.ownerDocument||a).defaultView,"ampdoc").getAmpDoc(a):a}function y(a){a=x(a);return a.isSingleDoc()?a.win:a}
function w(a,b){ra(a,b);var c=ua(a);a=c[b];a.obj||(a.obj=new a.ctor(a.context),a.ctor=null,a.context=null,a.resolve&&a.resolve(a.obj));return a.obj}function ta(a,b){var c=ua(a)[b];if(c){if(c.promise)return c.promise;w(a,b);return c.promise=Promise.resolve(c.obj)}return null}function ua(a){var b=a.services;b||(b=a.services={});return b}function ra(a,b){a=a.services&&a.services[b];return!(!a||!a.ctor&&!a.obj)}
function va(){var a=new ha,b=a,c=b.promise,d=b.resolve;b=b.reject;c.catch(function(){});return{obj:null,promise:c,resolve:d,reject:b,context:null,ctor:null}};/*
 https://mths.be/cssescape v1.5.1 by @mathias | MIT license */
var wa=/(\0)|^(-)$|([\x01-\x1f\x7f]|^-?[0-9])|([\x80-\uffff0-9a-zA-Z_-]+)|[^]/g;function xa(a,b,c,d,e){return e?e:b?"\ufffd":d?a.slice(0,-1)+"\\"+a.slice(-1).charCodeAt(0).toString(16)+" ":"\\"+a};var ya;var za=Object.prototype.hasOwnProperty;function B(){var a,b=Object.create(null);a&&Object.assign(b,a);return b}function C(a){return a||{}}
function Aa(a,b){var c=void 0===c?10:c;var d=[],e=[];e.push({t:a,s:b,d:0});for(a={};0<e.length;){b=e.shift();a.G=b.t;a.B=b.s;a.T=b.d;if(d.includes(a.B))throw Error("Source object has a circular reference.");d.push(a.B);a.G!==a.B&&(a.T>c?Object.assign(a.G,a.B):Object.keys(a.B).forEach(function(a){return function(b){var c=a.B[b];if(za.call(a.G,b)){var d=a.G[b];if(qa(c)&&qa(d)){e.push({t:d,s:c,d:a.T+1});return}}a.G[b]=c}}(a)));a={B:a.B,G:a.G,T:a.T}}};function Ba(a,b){return b.length>a.length?!1:0==a.lastIndexOf(b,0)};function Ca(a,b){for(var c=[],d=a.parentElement;d;d=d.parentElement)b(d)&&c.push(d);return c}function Da(a){var b="fieldset";/^[\w-]+$/.test(b);b=b.toUpperCase();return Ca(a,function(a){return a.tagName==b})}function D(a,b){for(var c=a.length,d=0;d<c;d++)b(a[d],d)};function Ea(a,b,c){var d=sa(a,b);if(d)return d;var e=x(a);return e.whenBodyAvailable().then(function(){var a=e.win;var b=e.win.document.head;if(b){var d=[];b=b.querySelectorAll("script[custom-element]");for(var k=0;k<b.length;k++)d.push(b[k].getAttribute("custom-element"))}else d=[];a=d.includes(c)?z(a,"extensions").waitForExtension(a,c):Promise.resolve();return a}).then(function(){var d=e.win;if(d.ampExtendedElements&&d.ampExtendedElements[c]){d=y(a);var g=ta(d,b);g?d=g:(d=ua(d),d[b]=va(),d=d[b].promise)}else d=
null;return d})};function E(a){return A(a,"resources")};var F,Fa="Webkit webkit Moz moz ms O o".split(" ");function Ga(a,b,c){var d;var e=a.style;if(!Ba(b,"--")){F||(F=B());var f=F[b];if(!f){f=b;if(void 0===e[b]){var g=b.charAt(0).toUpperCase()+b.slice(1);b:{for(var h=0;h<Fa.length;h++){var k=Fa[h]+g;if(void 0!==e[k]){g=k;break b}}g=""}void 0!==e[g]&&(f=g)}F[b]=f}b=f}b&&(a.style[b]=d?c+d:c)}function Ha(a,b){void 0===b&&(b=a.hasAttribute("hidden"));b?a.removeAttribute("hidden"):a.setAttribute("hidden","")};var G;function Ia(a,b,c){var d=void 0,e=a,f=c;var g=function(a){try{return f(a)}catch(Z){throw self.reportError(Z),Z;}};var h=Ja(),k=!1;d&&(k=d.capture);e.addEventListener(b,g,h?d:k);return function(){e&&e.removeEventListener(b,g,h?d:k);g=e=f=null}}function Ja(){if(void 0!==G)return G;G=!1;try{var a={get capture(){G=!0}};self.addEventListener("test-options",null,a);self.removeEventListener("test-options",null,a)}catch(b){}return G};function Ka(a,b,c,d){var e={detail:c};Object.assign(e,d);if("function"==typeof a.CustomEvent)return new a.CustomEvent(b,e);a=a.document.createEvent("CustomEvent");a.initCustomEvent(b,!!e.bubbles,!!e.cancelable,c);return a}function La(a,b,c){return Ia(a,b,c)}function Ma(a,b){var c=b,d=Ia(a,"mouseup",function(a){try{c(a)}finally{c=null,d()}});return d}function Na(a){var b,c,d=new Promise(function(b){c=Ma(a,b)});d.then(c,c);b&&b(c);return d};function Oa(a,b){function c(c){g=null;f=a.setTimeout(d,e);b.apply(null,c)}function d(){f=0;g&&c(g)}var e=100,f=0,g=null;return function(a){for(var b=[],d=0;d<arguments.length;++d)b[d-0]=arguments[d];f?g=b:c(b)}};function Pa(a){var b=a.getRootNode();this.wa=b.ownerDocument||b;this.l=this.wa.defaultView;this.ia=A(a,"viewport");this.P=[];this.P.push(La(b,"input",function(a){a=a.target;"TEXTAREA"==a.tagName&&a.hasAttribute("autoexpand")&&Qa(a)}));this.P.push(La(b,"mousedown",function(a){1==a.which&&(a=a.target,"TEXTAREA"==a.tagName&&a.hasAttribute("autoexpand")&&Ra(a))}));var c=b.querySelectorAll("textarea");this.P.push(La(b,"amp:dom-update",function(){c=b.querySelectorAll("textarea")}));var d=Oa(this.l,function(a){a.relayoutAll&&
Sa(c)});this.P.push(this.ia.onResize(d));D(c,function(a){Ta(a).then(function(b){b&&(r().warn("AMP-FORM",'"textarea[autoexpand]" with initially scrolling content will not autoexpand.\nSee https://github.com/ampproject/amphtml/issues/20839'),a.removeAttribute("autoexpand"))})})}function Ua(a){function b(){var b=c.querySelector("textarea[autoexpand]");b&&!d?d=new Pa(a):!b&&d&&(d.dispose(),d=null)}var c=a.getRootNode(),d=null;Ia(c,"amp:dom-update",b);b()}Pa.prototype.dispose=function(){this.P.forEach(function(a){return a()})};
function Ta(a){var b=E(a);return b.measureElement(function(){return a.scrollHeight>a.clientHeight})}function Sa(a){D(a,function(a){"TEXTAREA"==a.tagName&&a.hasAttribute("autoexpand")&&Qa(a)})}function Ra(a){var b=E(a);Promise.all([b.measureElement(function(){return a.scrollHeight}),Na(a)]).then(function(c){var d=c[0],e=0;return b.measureMutateElement(a,function(){e=a.scrollHeight},function(){d!=e&&a.removeAttribute("autoexpand")})})}
function Qa(a){var b=E(a),c=a.ownerDocument.defaultView,d=0,e=0,f=0,g=Va(a);b.measureMutateElement(a,function(){var b=c.getComputedStyle(a)||B();e=a.scrollHeight;var k=parseInt(b.getPropertyValue("max-height"),10);f=isNaN(k)?Infinity:k;d="content-box"==b.getPropertyValue("box-sizing")?-parseInt(b.getPropertyValue("padding-top"),10)+-parseInt(b.getPropertyValue("padding-bottom"),10):parseInt(b.getPropertyValue("border-top-width"),10)+parseInt(b.getPropertyValue("border-bottom-width"),10)},function(){return g.then(function(b){a.classList.toggle("i-amphtml-textarea-max",
b+d>f);var c="iAmphtmlHasExpanded"in a.dataset,g=c||e<=b;g&&(a.dataset.iAmphtmlHasExpanded="",Ga(a,"height",b+d+"px"))})})}
function Va(a){var b=a.ownerDocument,c=b.defaultView,d=b.body,e=E(a),f=a.cloneNode(!1);f.classList.add("i-amphtml-textarea-clone");var g=0,h=!1;return e.measureMutateElement(d,function(){var b=c.getComputedStyle(a)||B();b=parseInt(b.getPropertyValue("max-height"),10);h=isNaN(b)||a.scrollHeight<b},function(){h&&(a.scrollTop=0);b.body.appendChild(f)}).then(function(){return e.measureMutateElement(d,function(){g=f.scrollHeight},function(){var a=f;a.parentElement&&a.parentElement.removeChild(a)})}).then(function(){return g})}
;function Wa(a,b){return a.hasAttribute("verify-xhr")?new Xa(a,b):new Ya(a)}function H(a){this.h=a}H.prototype.onCommit=function(){Za(this);return ab(this)?this.qa():Promise.resolve({updatedElements:[],errors:[]})};H.prototype.qa=function(){return Promise.resolve({updatedElements:[],errors:[]})};
function ab(a){a=a.h.elements;for(var b=0;b<a.length;b++){var c=a[b];if(!c.disabled)switch(c.type){case "select-multiple":case "select-one":c=c.options;for(var d=0;d<c.length;d++)if(c[d].selected!==c[d].defaultSelected)return!0;break;case "checkbox":case "radio":if(c.checked!==c.defaultChecked)return!0;break;default:if(c.value!==c.defaultValue)return!0}}return!1}function Za(a){(a=a.h.elements)&&D(a,function(a){a.setCustomValidity("")})}function Ya(a){H.apply(this,arguments)}n(Ya,H);
function Xa(a,b){this.h=a;this.X=b;this.S=null;this.ka=[]}n(Xa,H);Xa.prototype.qa=function(){var a=this,b=this.X().then(function(){return[]},function(a){return bb(a)});return cb(this,b).then(function(b){return db(a,b)})};function cb(a,b){if(!a.S){a.S=new ja;var c=function(){return a.S=null};a.S.then(c,c)}return a.S.add(b)}
function db(a,b){function c(a){return b.every(function(b){return a.name!==b.name})}var d=[],e=a.ka;a.ka=b;for(var f=0;f<b.length;f++){var g=b[f],h=r().assertString(g.name,"Verification errors must have a name property");g=r().assertString(g.message,"Verification errors must have a message property");h=r().assertElement(a.h.querySelector('[name="'+h+'"]'),"Verification error name property must match a field name");h.checkValidity()&&(h.setCustomValidity(g),d.push(h))}var k=e.filter(c).map(function(b){return a.h.querySelector('[name="'+
b.name+'"]')});return{updatedElements:d.concat(k),errors:b}}function bb(a){return(a=a.response)?a.json().then(function(a){return a.verifyErrors||[]},function(){return[]}):Promise.resolve([])};function eb(){this.o=null}l=eb.prototype;l.add=function(a){var b=this;this.o||(this.o=[]);this.o.push(a);return function(){b.remove(a)}};l.remove=function(a){this.o&&(a=this.o.indexOf(a),-1<a&&this.o.splice(a,1))};l.removeAll=function(){this.o&&(this.o.length=0)};l.fire=function(a){if(this.o)for(var b=this.o,c=0;c<b.length;c++)(0,b[c])(a)};l.getHandlerCount=function(){return this.o?this.o.length:0};function fb(){this.ja=new eb}fb.prototype.beforeSubmit=function(a){return this.ja.add(a)};fb.prototype.fire=function(a){this.ja.fire(a)};function gb(){var a=100;this.va=a;this.ba=this.ha=0;this.W=Object.create(null)}gb.prototype.has=function(a){return!!this.W[a]};gb.prototype.get=function(a){var b=this.W[a];if(b)return b.access=++this.ba,b.payload};gb.prototype.put=function(a,b){this.has(a)||this.ha++;this.W[a]={payload:b,access:this.ba};if(!(this.ha<=this.va)){t().warn("lru-cache","Trimming LRU cache");a=this.W;var c=this.ba+1,d;for(d in a){var e=a[d].access;if(e<c){c=e;var f=d}}void 0!==f&&(delete a[f],this.ha--)}};var I=self.AMP_CONFIG||{},hb={thirdParty:I.thirdPartyUrl||"https://3p.ampproject.net",thirdPartyFrameHost:I.thirdPartyFrameHost||"ampproject.net",thirdPartyFrameRegex:("string"==typeof I.thirdPartyFrameRegex?new RegExp(I.thirdPartyFrameRegex):I.thirdPartyFrameRegex)||/^d-\d+\.ampproject\.net$/,cdn:I.cdnUrl||"https://cdn.ampproject.org",cdnProxyRegex:("string"==typeof I.cdnProxyRegex?new RegExp(I.cdnProxyRegex):I.cdnProxyRegex)||/^https:\/\/([a-zA-Z0-9_-]+\.)?cdn\.ampproject\.org$/,localhostRegex:/^https?:\/\/localhost(:\d+)?$/,
errorReporting:I.errorReportingUrl||"https://amp-error-reporting.appspot.com/r",localDev:I.localDev||!1};var ib=C({c:!0,v:!0,a:!0,ad:!0,action:!0}),jb,kb,lb=/[?&]amp_js[^&]*/,mb=/[?&]amp_gsa[^&]*/,nb=/[?&]amp_r[^&]*/,ob=/[?&]amp_kit[^&]*/,pb=/[?&]usqp[^&]*/;
function J(a){var b;jb||(jb=self.document.createElement("a"),kb=self.UrlCache||(self.UrlCache=new gb));var c=b?null:kb,d=jb;if(c&&c.has(a))a=c.get(a);else{d.href=a;d.protocol||(d.href=d.href);var e={href:d.href,protocol:d.protocol,host:d.host,hostname:d.hostname,port:"0"==d.port?"":d.port,pathname:d.pathname,search:d.search,hash:d.hash,origin:null};"/"!==e.pathname[0]&&(e.pathname="/"+e.pathname);if("http:"==e.protocol&&80==e.port||"https:"==e.protocol&&443==e.port)e.port="",e.host=e.hostname;e.origin=
d.origin&&"null"!=d.origin?d.origin:"data:"!=e.protocol&&e.host?e.protocol+"//"+e.host:e.href;d=p().test&&Object.freeze?Object.freeze(e):e;c&&c.put(a,d);a=d}return a}function qb(a,b,c){if(!b)return a;var d=a.split("#",2),e=d[0].split("?",2),f=e[0]+(e[1]?c?"?"+b+"&"+e[1]:"?"+e[1]+"&"+b:"?"+b);return f+=d[1]?"#"+d[1]:""}
function rb(a){var b=[],c;for(c in a){var d=a[c];if(null!=d)if(Array.isArray(d))for(var e=0;e<d.length;e++){var f=d[e];b.push(encodeURIComponent(c)+"="+encodeURIComponent(f))}else e=d,b.push(encodeURIComponent(c)+"="+encodeURIComponent(e))}return b.join("&")}
function sb(a){"string"==typeof a&&(a=J(a));var b=a;"string"==typeof b&&(b=J(b));if(!hb.cdnProxyRegex.test(b.origin))return a.href;b=a.pathname.split("/");u(ib[b[1]],"Unknown path prefix in url %s",a.href);var c=b[2],d="s"==c?"https://"+decodeURIComponent(b[3]):"http://"+decodeURIComponent(c);u(0<d.indexOf("."),"Expected a . in origin %s",d);b.splice(1,"s"==c?3:2);b=d+b.join("/");var e;e=(e=a.search)&&"?"!=e?(e=e.replace(lb,"").replace(mb,"").replace(nb,"").replace(ob,"").replace(pb,"").replace(/^[?&]/,
""))?"?"+e:"":"";return b+e+(a.hash||"")};function K(a){for(var b=a.elements,c={},d=/^(?:input|select|textarea)$/i,e=/^(?:submit|button|image|file|reset)$/i,f=/^(?:checkbox|radio)$/i,g={},h=0;h<b.length;g={F:g.F},h++){var k=b[h],m=k,Z=m.checked;g.F=m.name;var Yb=m.multiple,Zb=m.options,$b=m.tagName,$a=m.type;m=m.value;!g.F||tb(k)||!d.test($b)||e.test($a)||f.test($a)&&!Z||(void 0===c[g.F]&&(c[g.F]=[]),Yb?D(Zb,function(a){return function(b){b.selected&&c[a.F].push(b.value)}}(g)):c[g.F].push(m))}var Q=ub(a);Q&&Q.name&&(a=Q.name,void 0===c[a]&&
(c[a]=[]),c[Q.name].push(Q.value));Object.keys(c).forEach(function(a){0==c[a].length&&delete c[a]});return c}function ub(a){var b=a.elements,c=b.length,d=a.ownerDocument.activeElement,e=null;for(a=0;a<c;a++){var f=b[a],g=f.type;if("BUTTON"==f.tagName||"submit"==g)if(e||(e=f),d==f)return d}return e}function tb(a){if(a.disabled)return!0;a=Da(a);for(var b=0;b<a.length;b++)if(a[b].disabled)return!0;return!1};function vb(a,b){var c=z(a,"platform");return c.isIos()&&11==c.getMajorVersion()?new wb(b):FormData.prototype.entries&&FormData.prototype.delete?new L(b):new M(b)}function M(a){this.C=a?K(a):B()}M.prototype.append=function(a,b){var c=String(a);this.C[c]=this.C[c]||[];this.C[c].push(String(b))};M.prototype.delete=function(a){delete this.C[a]};
M.prototype.entries=function(){var a=this,b=[];Object.keys(this.C).forEach(function(c){a.C[c].forEach(function(a){return b.push([c,a])})});var c=0;return{next:function(){return c<b.length?{value:b[c++],done:!1}:{value:void 0,done:!0}}}};M.prototype.getFormData=function(){var a=this,b=new FormData;Object.keys(this.C).forEach(function(c){a.C[c].forEach(function(a){return b.append(c,a)})});return b};function L(a){this.D=new FormData(a);a&&(a=ub(a))&&this.append(a.name,a.value)}
L.prototype.append=function(a,b){this.D.append(a,b)};L.prototype.delete=function(a){this.D.delete(a)};L.prototype.entries=function(){return this.D.entries()};L.prototype.getFormData=function(){return this.D};function wb(a){L.call(this,a);var b=this;a&&D(a.elements,function(a){"file"==a.type&&0==a.files.length&&(b.D.delete(a.name),b.D.append(a.name,new Blob([]),""))})}n(wb,L);
wb.prototype.append=function(a,b,c){b&&"object"==typeof b&&""==b.name&&0==b.size?this.D.append(a,new Blob([]),c||""):this.D.append(a,b)};var xb=["GET","POST"];
function yb(a,b){u(qa(a),"Object expected: %s",a);var c="document"==b;if(!c)return new Response(a.body,a.init);var d=B(),e={status:200,statusText:"OK",getResponseHeader:function(a){return d[String(a).toLowerCase()]||null}};if(a.init){var f=a.init;Array.isArray(f.headers)&&f.headers.forEach(function(a){var b=a[0],c=a[1];d[String(b).toLowerCase()]=String(c)});f.status&&(e.status=parseInt(f.status,10));f.statusText&&(e.statusText=String(f.statusText))}return new Response(a.body?String(a.body):"",e)}
function zb(a){var b=a.getAttribute("cross-origin")||a.getAttribute("crossorigin");return b&&"amp-viewer-auth-token-via-post"===b.trim()?Ea(a,"amp-viewer-assistance","amp-viewer-assistance").then(function(a){u(a,'crossorigin="amp-viewer-auth-token-post" requires amp-viewer-assistance extension.');return a.getIdTokenPromise()}).then(function(a){return a||""}).catch(function(){return""}):Promise.resolve(void 0)};function N(a,b){var c="amp-form";this.L=a;this.A=b;this.Ba=c}N.prototype.isSupported=function(){var a=this.L.ampdoc;return a.isSingleDoc()&&a.getRootNode().documentElement.hasAttribute("allow-viewer-render-template")?this.L.hasCapability("viewerRenderTemplate"):!1};N.prototype.fetchAndRenderTemplate=function(a,b,c,d){c=void 0===c?null:c;d=void 0===d?{}:d;var e;c||(e=this.A.maybeFindTemplate(a));return this.L.sendMessageAwaitResponse("viewerRenderTemplate",Ab(this,b,e,c,d))};
N.prototype.renderTemplate=function(a,b){if(this.isSupported()){u("string"===typeof b.html,"Server side html response must be defined");var c=this.A.findAndSetHtmlForTemplate(a,b.html)}else c=Array.isArray(b)?this.A.findAndRenderTemplateArray(a,b):this.A.findAndRenderTemplate(a,b);return c};
function Ab(a,b,c,d,e){e=void 0===e?{}:e;var f=C({type:a.Ba}),g="successTemplate",h=d&&d[g]?d[g]:c;h&&(f[g]={type:"amp-mustache",payload:h.innerHTML});var k="errorTemplate",m=d&&d[k]?d[k]:null;m&&(f[k]={type:"amp-mustache",payload:m.innerHTML});e&&Object.assign(f,e);a=b.xhrUrl;c=b.fetchOpt;b=Object.assign({},c);if((d=c.body)&&"function"==typeof d.getFormData){c=c.body;b.headers["Content-Type"]="multipart/form-data;charset=utf-8";c=c.entries();d=[];for(e=c.next();!e.done;e=c.next())d.push(e.value);
b.body=d}return C({originalRequest:{input:a,init:b},ampComponent:f})}N.prototype.verifySsrResponse=function(a,b,c){b=yb(b,c.fetchOpt.responseType);c=c.fetchOpt;(b=b.headers.get("AMP-Access-Control-Allow-Source-Origin"))?(a=J(sb(a.location.href)).origin,u(b==a,"Returned AMP-Access-Control-Allow-Source-Origin is not equal to the current: "+b+(" vs "+a))):c.requireAmpResponseSourceOrigin&&u(!1,"Response must contain the AMP-Access-Control-Allow-Source-Origin header")};function Bb(a,b){this.ga=b;this.ia=A(a,"viewport");this.ra=z(a.win,"vsync");this.ea=null;this.da="";this.Z=!1;this.J=a.win.document.createElement("div");Ha(this.J,!1);this.J.classList.add("i-amphtml-validation-bubble");this.J.__BUBBLE_OBJ=this;a.getBody().appendChild(this.J)}Bb.prototype.isActiveOn=function(a){return this.Z&&a==this.ea};Bb.prototype.hide=function(){this.Z&&(this.Z=!1,this.ea=null,this.da="",this.ra.run({measure:void 0,mutate:Cb},{bubbleElement:this.J}))};
Bb.prototype.show=function(a,b){if(!this.isActiveOn(a)||b!=this.da){this.Z=!0;this.ea=a;this.da=b;var c={message:b,targetElement:a,bubbleElement:this.J,viewport:this.ia,id:this.ga};this.ra.run({measure:Db,mutate:Eb},c)}};function Cb(a){a.bubbleElement.removeAttribute("aria-alert");a.bubbleElement.removeAttribute("role");for(var b=a.bubbleElement;b.firstChild;)b.removeChild(b.firstChild);Ha(a.bubbleElement,!1)}function Db(a){a.targetRect=a.viewport.getLayoutRect(a.targetElement)}
function Eb(a){for(var b=a.bubbleElement;b.firstChild;)b.removeChild(b.firstChild);var c=a.bubbleElement.ownerDocument.createElement("div");c.id="bubble-message-"+a.id;c.textContent=a.message;a.bubbleElement.setAttribute("aria-labeledby",c.id);a.bubbleElement.setAttribute("role","alert");a.bubbleElement.setAttribute("aria-live","assertive");a.bubbleElement.appendChild(c);Ha(a.bubbleElement,!0);b=a.bubbleElement;a={top:a.targetRect.top-10+"px",left:a.targetRect.left+a.targetRect.width/2+"px"};for(var d in a)Ga(b,
d,a[d])};var Fb,Gb,Hb=0;function O(a){this.form=a;this.ampdoc=x(a);this.resources=E(a);this.root=this.ampdoc.getRootNode();this.Y=null}l=O.prototype;l.report=function(){};l.onBlur=function(){};l.onInput=function(){};l.inputs=function(){return this.form.querySelectorAll("input,select,textarea")};
l.checkInputValidity=function(a){if("TEXTAREA"===a.tagName&&a.hasAttribute("pattern")&&(a.checkValidity()||"Please match the requested format."===a.validationMessage)){var b=a.getAttribute("pattern"),c=new RegExp("^"+b+"$","m"),d=c.test(a.value);a.setCustomValidity(d?"":"Please match the requested format.")}return a.checkValidity()};l.checkFormValidity=function(a){Ib(this,a);return a.checkValidity()};l.reportFormValidity=function(a){Ib(this,a);return a.reportValidity()};
function Ib(a,b){D(b.elements,function(b){"TEXTAREA"==b.tagName&&a.checkInputValidity(b)})}l.fireValidityEventIfNecessary=function(){var a=this.Y;this.Y=this.checkFormValidity(this.form);if(a!==this.Y){var b=Ka(this.form.ownerDocument.defaultView,this.Y?"valid":"invalid",null,{bubbles:!0});this.form.dispatchEvent(b)}};function Jb(a){O.apply(this,arguments)}n(Jb,O);Jb.prototype.report=function(){this.reportFormValidity(this.form);this.fireValidityEventIfNecessary()};
function P(a){O.call(this,a);var b="i-amphtml-validation-bubble-"+Hb++;this.R=new Bb(this.ampdoc,b)}n(P,O);P.prototype.report=function(){for(var a=this.inputs(),b=0;b<a.length;b++)if(!this.checkInputValidity(a[b])){a[b].focus();this.R.show(a[b],a[b].validationMessage);break}this.fireValidityEventIfNecessary()};P.prototype.onBlur=function(a){"submit"!=a.target.type&&this.R.hide()};
P.prototype.onInput=function(a){a=a.target;this.R.isActiveOn(a)&&(this.checkInputValidity(a)?(a.removeAttribute("aria-invalid"),this.R.hide()):(a.setAttribute("aria-invalid","true"),this.R.show(a,a.validationMessage)))};function R(a){O.call(this,a)}n(R,O);l=R.prototype;l.reportInput=function(a){var b=Kb(a);b&&this.showValidationFor(a,b)};l.hideAllValidations=function(){for(var a=this.inputs(),b=0;b<a.length;b++)this.hideValidationFor(a[b])};
l.getValidationFor=function(a,b){if(!a.id)return null;"TEXTAREA"===a.tagName&&(b="patternMismatch");var c="__AMP_VALIDATION_"+b;c in a||(a[c]=this.root.querySelector("[visible-when-invalid="+b+"]"+("[validation-for="+a.id+"]")));return a[c]};
l.showValidationFor=function(a,b){var c=this.getValidationFor(a,b);c&&(c.textContent.trim()||(c.textContent=a.validationMessage),a.__AMP_VISIBLE_VALIDATION=c,this.resources.mutateElement(a,function(){return a.setAttribute("aria-invalid","true")}),this.resources.mutateElement(c,function(){return c.classList.add("visible")}))};
l.hideValidationFor=function(a){var b=this.getVisibleValidationFor(a);b&&(delete a.__AMP_VISIBLE_VALIDATION,this.resources.mutateElement(a,function(){return a.removeAttribute("aria-invalid")}),this.resources.mutateElement(b,function(){return b.classList.remove("visible")}))};l.getVisibleValidationFor=function(a){return a.__AMP_VISIBLE_VALIDATION};l.shouldValidateOnInteraction=function(){throw Error("Not Implemented");};
l.onInteraction=function(a){a=a.target;var b=!!a.checkValidity&&this.shouldValidateOnInteraction(a);this.hideValidationFor(a);b&&!this.checkInputValidity(a)&&this.reportInput(a)};l.onBlur=function(a){this.onInteraction(a)};l.onInput=function(a){this.onInteraction(a)};function Lb(a){R.apply(this,arguments)}n(Lb,R);Lb.prototype.report=function(){this.hideAllValidations();for(var a=this.inputs(),b=0;b<a.length;b++)if(!this.checkInputValidity(a[b])){this.reportInput(a[b]);a[b].focus();break}this.fireValidityEventIfNecessary()};
Lb.prototype.shouldValidateOnInteraction=function(a){return!!this.getVisibleValidationFor(a)};function S(a){R.apply(this,arguments)}n(S,R);S.prototype.report=function(){this.hideAllValidations();for(var a=null,b=this.inputs(),c=0;c<b.length;c++)this.checkInputValidity(b[c])||(a=a||b[c],this.reportInput(b[c]));a&&a.focus();this.fireValidityEventIfNecessary()};S.prototype.shouldValidateOnInteraction=function(a){return!!this.getVisibleValidationFor(a)};function Mb(a){R.apply(this,arguments)}n(Mb,R);
Mb.prototype.shouldValidateOnInteraction=function(){return!0};Mb.prototype.onInteraction=function(a){R.prototype.onInteraction.call(this,a);this.fireValidityEventIfNecessary()};function Nb(a){S.apply(this,arguments)}n(Nb,S);Nb.prototype.shouldValidateOnInteraction=function(){return!0};Nb.prototype.onInteraction=function(a){S.prototype.onInteraction.call(this,a);this.fireValidityEventIfNecessary()};
function Ob(a){var b=a.getAttribute("custom-validation-reporting");switch(b){case "as-you-go":return new Mb(a);case "show-all-on-submit":return new S(a);case "interact-and-submit":return new Nb(a);case "show-first-on-submit":return new Lb(a)}a.ownerDocument&&void 0===Fb&&(Fb=!!document.createElement("form").reportValidity);return Fb?new Jb(a):new P(a)}
function Kb(a){var b=["badInput"];for(c in a.validity)b.includes(c)||b.push(c);var c=b.filter(function(b){return!0===a.validity[b]});return c.length?c[0]:null};function Pb(a){var b=a.ownerDocument.defaultView;b.FormProxy||(b.FormProxy=Qb(b));var c=b.FormProxy,d=new c(a);"action"in d||Rb(a,d);a.$p=d}
function Qb(a){function b(a){this.h=a}var c=b.prototype,d=a.Object,e=d.prototype,f=[a.HTMLFormElement,a.EventTarget],g=f.reduce(function(a,b){for(b=b&&b.prototype;b&&b!==e&&!(0<=a.indexOf(b));)a.push(b),b=d.getPrototypeOf(b);return a},[]);g.forEach(function(b){var d={},f;for(f in b){d.w=a.Object.getOwnPropertyDescriptor(b,f);if(d.w&&f.toUpperCase()!=f&&!Ba(f,"on")&&!e.hasOwnProperty.call(c,f))if("function"==typeof d.w.value)d.aa=d.w.value,c[f]=function(a){return function(){return a.aa.apply(this.h,
arguments)}}(d);else{var g={};d.w.get&&(g.get=function(a){return function(){return a.w.get.call(this.h)}}(d));d.w.set&&(g.set=function(a){return function(b){return a.w.set.call(this.h,b)}}(d));a.Object.defineProperty(c,f,g)}d={aa:d.aa,w:d.w}}});return b}
function Rb(a,b){var c=a.ownerDocument.defaultView.HTMLFormElement.prototype.cloneNode.call(a,!1),d={},e;for(e in c){d.j=e;if(!(d.j in b||d.j.toUpperCase()==d.j||Ba(d.j,"on"))){d.m=Sb[d.j];var f=a[d.j];if(d.m)if(d.m.access==T){d.N=void 0;if(f&&f.nodeType){var g=c=f,h=g.nextSibling;g=g.parentNode;g.removeChild(c);try{d.N=a[d.j]}finally{g.insertBefore(c,h)}}else d.N=f;Object.defineProperty(b,d.j,{get:function(a){return function(){return a.N}}(d)})}else d.m.access==U&&(d.O=d.m.attr||d.j,Object.defineProperty(b,
d.j,{get:function(c){return function(){var d=b.getAttribute(c.O);return null==d&&void 0!==c.m.def?c.m.def:c.m.type==Tb?"true"===d:c.m.type==Ub?null!=d:c.m.type==Vb?(d=d||"",v(a,"url").parse(d).href):d}}(d),set:function(a){return function(c){a.m.type==Ub&&(c=c?"":null);null!=c?b.setAttribute(a.O,c):b.removeAttribute(a.O)}}(d)}));else Object.defineProperty(b,d.j,{get:function(b){return function(){return a[b.j]}}(d),set:function(b){return function(c){a[b.j]=c}}(d)})}d={N:d.N,O:d.O,m:d.m,j:d.j}}}
var U=1,T=2,Vb=1,Tb=2,Ub=3,Sb={acceptCharset:{access:U,attr:"accept-charset"},accessKey:{access:U,attr:"accesskey"},action:{access:U,type:Vb},attributes:{access:T},autocomplete:{access:U,def:"on"},children:{access:T},dataset:{access:T},dir:{access:U},draggable:{access:U,type:Tb,def:!1},elements:{access:T},encoding:{access:T},enctype:{access:U},hidden:{access:U,type:Ub,def:!1},id:{access:U,def:""},lang:{access:U},localName:{access:T},method:{access:U,def:"get"},name:{access:U},noValidate:{access:U,
attr:"novalidate",type:Ub,def:!1},prefix:{access:T},spellcheck:{access:U},style:{access:T},target:{access:U,def:""},title:{access:U},translate:{access:U}};function Wb(a,b){var c='form.amp-form-submit-error [submit-error],form.amp-form-submit-success [submit-success],form.amp-form-submitting [submitting]{display:block}textarea[autoexpand]:not(.i-amphtml-textarea-max){overflow:hidden!important}.i-amphtml-textarea-clone{visibility:hidden;position:absolute;top:-9999px;left:-9999px;height:0!important}.i-amphtml-validation-bubble{-webkit-transform:translate(-50%,-100%);transform:translate(-50%,-100%);background-color:#fff;box-shadow:0 5px 15px 0 rgba(0,0,0,0.5);max-width:200px;position:absolute;display:block;box-sizing:border-box;padding:10px;border-radius:5px}.i-amphtml-validation-bubble:after{content:" ";position:absolute;bottom:-8px;left:30px;width:0;height:0;border-left:8px solid transparent;border-right:8px solid transparent;border-top:8px solid #fff}[visible-when-invalid]{color:red}\n/*# sourceURL=/extensions/amp-form/0.1/amp-form.css*/',
d=!1,e="amp-form",f=a.getHeadNode(),g=Xb(f,ac(f,c),d||!1,e||null);if(b){var h=a.getRootNode();if(bc(h,g))b(g);else var k=setInterval(function(){bc(h,g)&&(clearInterval(k),b(g))},4)}}
function Xb(a,b,c,d){var e=a.__AMP_CSS_SM;e||(e=a.__AMP_CSS_SM=B());var f=!c&&d&&"amp-custom"!=d&&"amp-keyframes"!=d,g=c?"amp-runtime":f?"amp-extension="+d:null;if(g){var h=cc(a,e,g);if(h)return h.textContent!==b&&(h.textContent=b),h}var k=(a.ownerDocument||a).createElement("style");k.textContent=b;var m=null;c?k.setAttribute("amp-runtime",""):f?(k.setAttribute("amp-extension",d||""),m=cc(a,e,"amp-runtime")):(d&&k.setAttribute(d,""),m=a.lastChild);b=m;a.insertBefore(k,b?b.nextSibling:a.firstChild);
g&&(e[g]=k);return k}function cc(a,b,c){return b[c]?b[c]:(a=a.querySelector("style["+c+"]"))?b[c]=a:null}function ac(a,b){return(a=a.__AMP_CSS_TR)?a(b):b}function bc(a,b){var c=a.styleSheets;for(a=0;a<c.length;a++){var d=c[a];if(d.ownerNode==b)return!0}return!1};function dc(a,b,c){Ea(a,"amp-analytics-instrumentation","amp-analytics").then(function(d){d&&d.triggerEventForTarget(a,b,c)})};var ec=["amp-selector"];
function fc(a,b){var c=this;try{Pb(a)}catch(f){t().error("amp-form","form proxy failed to install",f)}a.__AMP_FORM=this;this.ga=b;this.l=a.ownerDocument.defaultView;this.Da=z(this.l,"timer");this.pa=v(a,"url-replace");this.fa=null;this.h=a;this.A=z(this.l,"templates");this.Ga=z(this.l,"xhr");this.V=v(this.h,"action");this.na=E(this.h);this.L=A(this.h,"viewer");this.K=new N(this.L,this.A);this.H=(this.h.getAttribute("method")||"GET").toUpperCase();this.Ca=this.h.getAttribute("target");this.M=gc(this,
"action-xhr");this.Fa=gc(this,"verify-xhr");this.oa=!this.h.hasAttribute("novalidate");this.h.setAttribute("novalidate","");this.oa||this.h.setAttribute("amp-novalidate","");this.h.classList.add("i-amphtml-form");this.I="initial";b=this.h.elements;for(var d=0;d<b.length;d++){var e=b[d].name;u("__amp_source_origin"!=e&&"__amp_form_verify"!=e,"Illegal input name, %s found: %s",e,b[d])}this.$=Ob(this.h);this.Ea=Wa(this.h,function(){return hc(c)});this.V.installActionHandler(this.h,this.ua.bind(this));
ic(this);jc(this);this.ma=this.ta=null;this.xa=A(a,"form-submit-service")}function gc(a,b){var c=a.h.getAttribute(b);if(c){var d=v(a.h,"url");d.assertHttpsUrl(c,a.h,b);u(!d.isProxyOrigin(c),"form %s should not be on AMP CDN: %s",b,a.h)}return c}l=fc.prototype;
l.requestForFormFetch=function(a,b,c,d){var e="GET"==b||"HEAD"==b;if(e){kc(this);var f=K(this.h);d&&d.forEach(function(a){delete f[a]});c&&Aa(f,c);var g=qb(a,rb(f))}else{g=a;var h=vb(this.l,this.h);d&&d.forEach(function(a){h.delete(a)});for(var k in c)h.append(k,c[k])}var m={xhrUrl:g,fetchOpt:C({body:h,method:b,credentials:"include",headers:C({Accept:"application/json"})})};return zb(this.h).then(function(a){a&&(u("POST"==m.fetchOpt.method,"Cannot attach auth token with GET request."),h.append("ampViewerAuthToken",
a));return m})};l.setXhrAction=function(a){this.M=a};l.ua=function(a){var b=this;if(!a.satisfiesTrust(100))return null;if("submit"==a.method)return lc(this).then(function(){var c=a;return"submitting"!=b.I&&mc(b)?nc(b,c.trust,null):Promise.resolve(null)});"clear"===a.method&&oc(this);return null};function lc(a){if(a.fa)return a.fa;var b=a.h.querySelectorAll(ec.join(",")),c=pa(b).map(function(a){return a.whenBuilt()});return a.fa=pc(a,c,2E3)}
function ic(a){a.L.whenNextVisible().then(function(){var b=a.h.querySelector("[autofocus]");if(b)try{b.focus()}catch(c){}});a.h.addEventListener("submit",a.ya.bind(a),!0);a.h.addEventListener("blur",function(b){qc(b.target);a.$.onBlur(b)},!0);a.K.isSupported()||a.h.addEventListener("change",function(b){a.Ea.onCommit().then(function(c){var d=c.updatedElements,e=c.errors;d.forEach(qc);a.$.onBlur(b);"verifying"===a.I&&(e.length?(V(a,"verify-error"),W(a,{verifyErrors:e}).then(function(){X(a,"verify-error",
e)})):V(a,"initial"))})});a.h.addEventListener("input",function(b){qc(b.target);a.$.onInput(b)})}function jc(a){Ea(a.h,"inputmask","amp-inputmask").then(function(a){a&&a.install()})}function rc(a,b){sc(a,"Form analytics not supported");var c=C({}),d=K(a.h),e;for(e in d)Object.prototype.hasOwnProperty.call(d,e)&&(c["formFields["+e+"]"]=d[e].join(","));c.formId=a.h.id;dc(a.h,b,c)}
function oc(a){a.h.reset();V(a,"initial");a.h.classList.remove("user-valid");a.h.classList.remove("user-invalid");var b=a.h.querySelectorAll(".user-valid, .user-invalid");D(b,function(a){a.classList.remove("user-valid");a.classList.remove("user-invalid")});var c=a.h.querySelectorAll(".visible[validation-for]");D(c,function(a){a.classList.remove("visible")});tc(a.h)}
l.ya=function(a){if("submitting"==this.I||!mc(this))return a.stopImmediatePropagation(),a.preventDefault(),Promise.resolve(null);(this.M||"POST"==this.H)&&a.preventDefault();return nc(this,100,a)};
function nc(a,b,c){try{var d={form:a.h,actionXhrMutator:a.setXhrAction.bind(a)};a.xa.fire(d)}catch(k){t().error("amp-form","Form submit service failed: %s",k)}var e=uc(a),f=a.h.getElementsByClassName("i-amphtml-async-input");if(!a.M&&"GET"==a.H){sc(a,"Non-XHR GETs not supported.");kc(a);if(0===f.length){for(d=0;d<e.length;d++)a.pa.expandInputValueSync(e[d]);var g=!c;vc(a,g);return Promise.resolve()}c&&c.preventDefault()}V(a,"submitting");var h=[];h.push(wc(a,e));D(f,function(b){h.push(xc(a,b))});
return pc(a,h,1E4).then(function(){if(a.M)var c=yc(a,b);else"POST"==a.H?u(!1,"Only XHR based (via action-xhr attribute) submissions are supported for POST requests. %s",a.h):"GET"==a.H&&vc(a,!0),c=Promise.resolve();return c},function(b){return zc(a,b)})}function uc(a){return a.h.querySelectorAll('[type="hidden"][data-amp-replace]')}function zc(a,b){V(a,"submit-error");t().error("amp-form","Form submission failed: %s",b);var c=C({error:b.message});W(a,c).then(function(){X(a,"submit-error",b)})}
function hc(a){if("submitting"===a.I)return Promise.resolve();V(a,"verifying");X(a,"verify",null);return wc(a,uc(a)).then(function(){return Ac(a)})}function yc(a,b){a.K.isSupported()?b=Bc(a,b):(Cc(a,b),b=a.X(a.M,a.H).then(function(b){return Dc(a,b)},function(b){return Ec(a,b)}));p().test&&(a.ta=b);return b}
function Bc(a,b){var c,d=K(a.h);return W(a,d).then(function(){return a.V.trigger(a.h,"submit",null,b)}).then(function(){return a.requestForFormFetch(a.M,a.H)}).then(function(b){var d=c=b,e=c.fetchOpt||{};var h=e.method;void 0===h?h="GET":(h=h.toUpperCase(),xb.includes(h));e.method=h;e.headers=e.headers||C({});d.fetchOpt=e;d=c;var k=a.l;h=c.xhrUrl;e=c.fetchOpt;!1===e.ampCors&&(e.requireAmpResponseSourceOrigin=!1);!0===e.requireAmpResponseSourceOrigin&&t().error("XHR","requireAmpResponseSourceOrigin is deprecated, use ampCors instead");
void 0===e.requireAmpResponseSourceOrigin&&(e.requireAmpResponseSourceOrigin=!0);k=k.origin||J(k.location.href).origin;h=J(h).origin;k==h&&(e.headers=e.headers||{},e.headers["AMP-Same-Origin"]="true");d.fetchOpt=e;d=c;e=c.xhrUrl;!1!==c.fetchOpt.ampCors&&(h=a.l,k=J(e),k=ma(k.search),u(!("__amp_source_origin"in k),"Source origin is not allowed in %s",e),h=J(sb(h.location.href)).origin,h=encodeURIComponent("__amp_source_origin")+"="+encodeURIComponent(h),e=qb(e,h,void 0));d.xhrUrl=e;return a.K.fetchAndRenderTemplate(a.h,
c,Fc(a))}).then(function(b){return Gc(a,b,c)},function(b){return Hc(a,b)})}function Fc(a){var b=a.h.querySelector("div[submit-success]"),c=a.h.querySelector("div[submit-error]"),d,e;b&&(d=a.A.maybeFindTemplate(b));c&&(e=a.A.maybeFindTemplate(c));return{successTemplate:d,errorTemplate:e}}function Hc(a,b){V(a,"submit-error");r().error("amp-form","Form submission failed: %s",b);return ia(function(){W(a,b||{}).then(function(){X(a,"submit-error",b)})})}
function Cc(a,b){rc(a,"amp-form-submit");var c=K(a.h);W(a,c).then(function(){a.V.trigger(a.h,"submit",null,b)})}function wc(a,b){for(var c=[],d=0;d<b.length;d++)c.push(a.pa.expandInputValueAsync(b[d]));return pc(a,c,100)}
function xc(a,b){return b.getImpl().then(function(a){return a.getValue()}).then(function(c){var d=b.getAttribute("name");d=a.h.querySelector("input[name="+String(d).replace(wa,xa)+"]");if(!d){d=C({name:b.getAttribute("name"),hidden:"true"});var e=a.l.document.createElement("input"),f;for(f in d)e.setAttribute(f,d[f]);d=e}d.setAttribute("value",c);a.h.appendChild(d)})}
function Ac(a){var b=pa(a.h.querySelectorAll("["+"no-verify".replace(wa,xa)+"]")),c=b.map(function(a){return a.name||a.id}),d={};return a.X(a.Fa,a.H,(d.__amp_form_verify=!0,d),c)}l.X=function(a,b,c,d){var e=this;sc(this,"XHRs should be proxied.");return this.requestForFormFetch(a,b,c,d).then(function(a){return e.Ga.fetch(a.xhrUrl,a.fetchOpt)})};function Gc(a,b,c){a.K.verifySsrResponse(a.l,b,c);return Ic(a,ia(function(){return b}))}
function Dc(a,b){return Ic(a,b.json()).then(function(){rc(a,"amp-form-submit-success");Jc(a,b)})}function Ic(a,b){return b.then(function(b){V(a,"submit-success");W(a,b||{}).then(function(){X(a,"submit-success",b)})},function(a){r().error("amp-form","Failed to parse response JSON: %s",a)})}
function Ec(a,b){return(b&&b.response?b.response.json().catch(function(){return null}):Promise.resolve(null)).then(function(c){rc(a,"amp-form-submit-error");V(a,"submit-error");W(a,c||{}).then(function(){X(a,"submit-error",c)});Jc(a,b.response);r().error("amp-form","Form submission failed: %s",b)})}function vc(a,b){rc(a,"amp-form-submit");b&&a.h.submit();V(a,"initial")}function sc(a,b){var c=a.K.isSupported();u(!1===c,"[amp-form]: viewerRenderTemplate | %s",b)}
function kc(a){var b=a.h.querySelectorAll("input[type=password],input[type=file]");u(0==b.length,"input[type=password] or input[type=file] may only appear in form[method=post]")}function mc(a){void 0===Gb&&(Gb=!!a.l.document.createElement("input").checkValidity);if(Gb){var b=Kc(a.h);if(a.oa)return a.$.report(),b}return!0}
function Jc(a,b){sc(a,"Redirects not supported.");if(b&&b.headers){var c=b.headers.get("AMP-Redirect-To");if(c){u("_blank"!=a.Ca,"Redirecting to target=_blank using AMP-Redirect-To is currently not supported, use target=_top instead. %s",a.h);try{var d=v(a.h,"url");d.assertAbsoluteHttpOrHttpsUrl(c);d.assertHttpsUrl(c,"AMP-Redirect-To","Url")}catch(e){u(!1,"The `AMP-Redirect-To` header value must be an absolute URL starting with https://. Found %s",c)}A(a.h,"navigation").navigateTo(a.l,c,"AMP-Redirect-To")}}}
function X(a,b,c){c=Ka(a.l,"amp-form."+b,C({response:c}));a.V.trigger(a.h,b,c,100)}function pc(a,b,c){return Promise.race([Promise.all(b),a.Da.promise(c)])}
function V(a,b){var c=a.I;a.h.classList.remove("amp-form-"+c);a.h.classList.add("amp-form-"+b);var d=a.h.querySelector("["+c+"]");if(d){/^[\w-]+$/.test("i-amphtml-rendered");if(void 0!==ya)var e=ya;else{try{var f=d.ownerDocument,g=f.createElement("div"),h=f.createElement("div");g.appendChild(h);e=g.querySelector(":scope div")===h}catch(k){e=!1}e=ya=e}e?d=d.querySelector("> [i-amphtml-rendered]".replace(/^|,/g,"$&:scope ")):(d.classList.add("i-amphtml-scoped"),e="> [i-amphtml-rendered]".replace(/^|,/g,
"$&.i-amphtml-scoped "),e=d.querySelectorAll(e),d.classList.remove("i-amphtml-scoped"),d=void 0===e[0]?null:e[0]);d&&d.parentElement&&d.parentElement.removeChild(d)}a.I=b}
function W(a,b){var c=a.h.querySelector("["+a.I+"]"),d=Promise.resolve();if(c){var e="rendered-message-"+a.ga;c.setAttribute("role","alert");c.setAttribute("aria-labeledby",e);c.setAttribute("aria-live","assertive");a.A.hasTemplate(c)?d=a.K.renderTemplate(c,b).then(function(b){b.id=e;b.setAttribute("i-amphtml-rendered","");return a.na.mutateElement(c,function(){c.appendChild(b);var d=Ka(a.l,"amp:dom-update",null,{bubbles:!0});c.dispatchEvent(d)})}):a.na.mutateElement(c,function(){})}p().test&&(a.ma=
d);return d}l.Ha=function(){return this.ma};l.Ja=function(){return this.ta};function Kc(a){D(a.querySelectorAll("input,select,textarea,fieldset"),function(a){return Y(a)});return Y(a)}function tc(a){var b=document.createElement("input"),c={},d;for(d in b.validity){c.U=d;var e=a.querySelectorAll("."+String(c.U).replace(wa,xa));D(e,function(a){return function(b){b.classList.remove(a.U)}}(c));c={U:c.U}}}
function Y(a,b){b=void 0===b?!1:b;if(!a.checkValidity)return!0;var c=!1,d=a.classList.contains("user-valid")?"valid":a.classList.contains("user-invalid")?"invalid":"none",e=a.checkValidity();"valid"!=d&&e?(a.classList.add("user-valid"),a.classList.remove("user-invalid"),c="invalid"==d):"invalid"==d||e||(a.classList.add("user-invalid"),a.classList.remove("user-valid"),c=!0);if(a.validity)for(var f in a.validity)a.classList.toggle(f,a.validity[f]);if(b&&c){f=Da(a);for(var g=0;g<f.length;g++)Y(f[g]);
a.form&&Y(a.form)}return e}function qc(a){Y(a,!0)}function Lc(a){this.sa=Mc(a).then(function(){return Nc(a)});p().test&&this.sa.then(function(){var b=a.win,c=Ka(b,"amp:form-service:initialize",null,{bubbles:!0});b.dispatchEvent(c)})}Lc.prototype.whenInitialized=function(){return this.sa};function Mc(a){var b=new ha;Wb(a,b.resolve);return b.promise}function Nc(a){return a.whenReady().then(function(){var b=a.getRootNode();Oc(b.querySelectorAll("form"));Ua(a);Pc(b)})}
function Oc(a){a&&D(a,function(a,c){var b=a.__AMP_FORM||null;b||new fc(a,"amp-form-"+c)})}function Pc(a){a.addEventListener("amp:dom-update",function(){Oc(a.querySelectorAll("form"))})}(function(a){a.registerServiceForDoc("form-submit-service",fb);a.registerServiceForDoc("amp-form",Lc)})(self.AMP);
})});

//# sourceMappingURL=amp-form-0.1.js.map
